### ISSUE TITLE
Can we use this image captioner? 

### ISSUE THREAD

**Issue by FurkanGozukara** [InternLM/InternLM-XComposer#1]
So that captioned images can be used to train stable diffusion

If so how to use as image captioner?

**Comment by LightDXY** [comment]
Hi, thanks for your interest in our work, you could try the chat model with the instruction like 'describe the image in detail' to get a caption of the image.

**Comment by LightDXY** [comment]
The 4-bit model and user guidance are coming soon, we welcome any kind of sharing of our work. btw, image captioning is a small aspect of our model, we have updated a new video demo to show the Interleaved Text-Image Composition capability and rich knowledge of our model.

**Comment by FurkanGozukara** [comment]
> The 4-bit model and user guidance are coming soon, we welcome any kind of sharing of our work. btw, image captioning is a small aspect of our model, we have updated a new video demo to show the Interleaved Text-Image Composition capability and rich knowledge of our model.

please add example code for 4 bit loading with image captioning

thank you so much

**Comment by LightDXY** [comment]
hi, the 4-bit model is ready and here is an [example](https://github.com/InternLM/InternLM-XComposer/blob/main/examples/example_chat_4bit_en.py). Please refer to the [installation instructions](https://github.com/InternLM/InternLM-XComposer/blob/main/docs/install.md) for the environment requirement.
