### ISSUE TITLE
support for multiple GPU inference

### ISSUE THREAD

**Issue by pixas** [InternLM/InternLM-XComposer#10]
Hello, I am interested in your work and I am curious about how to run internlm-xcomposer-7b in an environment that only contains 24GB GPUs. I am looking forward to a new version of inference code that supports multiple gpu inference. 

Thank you

**Comment by Fake10086** [comment]
maybe: https://huggingface.co/docs/accelerate/v0.23.0/en/package_reference/big_modeling#accelerate.load_checkpoint_and_dispatch

**Comment by myownskyW7** [comment]
We will release a 4-bit quantization version very soon, which can readily run with less than 24GB GPUs.

**Comment by myownskyW7** [comment]
The 4-bit version is released https://github.com/InternLM/InternLM-XComposer/commit/844084264e6abd9680679201384eb454692d3e96. It can be run with GPU with >= 12GB memory.
