### ISSUE TITLE
Error when running share-cap_batch_infer

### ISSUE THREAD

**Issue by WLuLi** [InternLM/InternLM-XComposer#100]
AttributeError: 'InternLMXComposerTokenizer' object has no attribute 'sp_model'

I've tried to redownload tokenizer.model from huggingface manually, but this doesn't work

**Comment by WLuLi** [comment]
I resolved this by installing transformers==4.31.0, as my previous version of transformers was too high. Sorry for bothering you.

**Comment by ykj467422034** [comment]
@WLuLi Hello, please tell me how to run share-cap_batch_infer.py on the local server. I have downloaded "Lin-Chen/ShareCaptioner" to the server on huggingface.

**Comment by WLuLi** [comment]
> @WLuLi Hello, please tell me how to run share-cap_batch_infer.py on the local server. I have downloaded "Lin-Chen/ShareCaptioner" to the server on huggingface.

I used
model = AutoModelForCausalLM.from_pretrained(args.model_name, trust_remote_code=True, local_files_only=True).to(gpu).eval()
tokenizer = AutoTokenizer.from_pretrained(args.model_name, trust_remote_code=True, local_files_only=True)
and it works. (args.model_name is path of sharecaptioner on my local server)

**Comment by WLuLi** [comment]
@ykj467422034 maybe some internet error, you can try some output

**Comment by ykj467422034** [comment]
OK，thank you very much!

**Comment by RyanHuangNLP** [comment]
@WLuLi Does share-cap_batch_infer support multi-gpu inference

**Comment by WLuLi** [comment]
@RyanHuangNLP yes, i think it is possible to implement multi-GPU inference by oneself.  By the way, I am not an member of this project, just someone who is interested in this work.
