### ISSUE TITLE
Model architecture of Share-Captioner

### ISSUE THREAD

**Issue by gordonhu608** [InternLM/InternLM-XComposer#101]
Thanks for your great work in ShareGPT-4V, I'm wondering if the Model architecture of Share-Captioner is also LLaVA-1.5 based.

**Comment by xiaoachen98** [comment]
> Thanks for your great work in ShareGPT-4V, I'm wondering if the Model architecture of Share-Captioner is also LLaVA-1.5 based.

Thanks for your interest. Captioner is based on our pre-view InternLM-Xcomposer with a resolution of 448x448.
