### ISSUE TITLE
where from the llava_pretrain image?

### ISSUE THREAD

**Issue by daicver** [InternLM/InternLM-XComposer#102]
I have  a problem when I prepare the training data. I want to know this images from where? Thanks.
ShareGPT4V
├── ...
├── data
│   ├── llava
│   │   ├── llava_pretrain
│   │   │   ├── images

**Comment by xiaoachen98** [comment]
> I have a problem when I prepare the training data. I want to know this images from where? Thanks. ShareGPT4V ├── ... ├── data │ ├── llava │ │ ├── llava_pretrain │ │ │ ├── images

Hi. You can find these data [here](https://huggingface.co/datasets/liuhaotian/LLaVA-Pretrain)

**Comment by daicver** [comment]
OK, thanks.
