### ISSUE TITLE
mix665k 数据集部分 sample 无 'image' key

### ISSUE THREAD

**Issue by daicver** [InternLM/InternLM-XComposer#104]
sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json
mix665k数据集部分sample无key('image')
例如：
{'id': 'i6IyJda_0', 'model': '', 'conversations': [{'from': 'human', 'value': 'How to tell if a customer segment is well segmented? In 3 bullet points.'}, {'from': 'gpt', 'value': '1. Homogeneity: The segment should consist of customers who share similar characteristics and behaviors.\n2. Distinctiveness: The segment should be different from other segments in terms of their characteristics and behaviors.\n3. Stability: The segment should remain relatively stable over time and not change drastically. The characteristics and behaviors of customers within the segment should not change significantly.'}]}
我应该如何获取图像的地址，谢谢

**Comment by xiaoachen98** [comment]
> sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json mix665k数据集部分sample无key('image') 例如： {'id': 'i6IyJda_0', 'model': '', 'conversations': [{'from': 'human', 'value': 'How to tell if a customer segment is well segmented? In 3 bullet points.'}, {'from': 'gpt', 'value': '1. Homogeneity: The segment should consist of customers who share similar characteristics and behaviors.\n2. Distinctiveness: The segment should be different from other segments in terms of their characteristics and behaviors.\n3. Stability: The segment should remain relatively stable over time and not change drastically. The characteristics and behaviors of customers within the segment should not change significantly.'}]} 我应该如何获取图像的地址，谢谢

These samples originated from the ShareGPT dataset, a textual dataset.
