### ISSUE TITLE
Issue about pretrain loss

### ISSUE THREAD

**Issue by yiyexy** [InternLM/InternLM-XComposer#106]
Hi!
Thanks for the great work!
I encountered an issue during the pretraining stage.
I was fine-tuning the vision tower, the linear adapter, and the Large Language Model (LLM) in the pretraining stage. The loss decreased to around 0.7X at 0.02, but it suddenly spiked to over 20. After some time, it gradually decreased to around 6.x. Is this normal? And why did this happen?
![image](https://github.com/InternLM/InternLM-XComposer/assets/35927125/00d978be-1fbd-45b8-add5-3c7ced9ce750)

<img width="506" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/35927125/f2b43797-23e5-4686-85bf-80ec23c225bc">

**Comment by xiaoachen98** [comment]
> Hi! Thanks for the great work! I encountered an issue during the pretraining stage. I was fine-tuning the vision tower, the linear adapter, and the Large Language Model (LLM) in the pretraining stage. The loss decreased to around 0.7X at 0.02, but it suddenly spiked to over 20. After some time, it gradually decreased to around 6.x. Is this normal? And why did this happen? ![image](https://private-user-images.githubusercontent.com/35927125/292370534-00d978be-1fbd-45b8-add5-3c7ced9ce750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1MzQtMDBkOTc4YmUtMWZiZC00NWI4LWFkZDUtM2M3Y2VkOWNlNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzJlYjJmZmVlMDdlNjI1ZTYyMDUzYTBkZThjNjMwMmU5YWQ1ZmJlZWI5NDU2YjU2YzFmZTQ0YzJjNWNlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tulX8K3axjDw6HZoxohIaN3uhhI6AUvEWbgrCiXWeCk)
> 
> <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/35927125/292370566-f2b43797-23e5-4686-85bf-80ec23c225bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1NjYtZjJiNDM3OTctMjNlNS00Njg2LTg1YmYtODBlYzIzYzIyNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTg5YjRjOTg5YjM4MmU4ZjQ0MjIwYTgxMDVlZmQxZGYzNzU2N2QzOThkZDZlYmM1Njk1NDk3MWYxZWE4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNo08aV6fyVa8gkaskBNRs9rK1POfvgKnTWUaKKCsCk">

It is so wired. Could you provide your training script? Have you modified any training code?

**Comment by yiyexy** [comment]
> > Hi! Thanks for the great work! I encountered an issue during the pretraining stage. I was fine-tuning the vision tower, the linear adapter, and the Large Language Model (LLM) in the pretraining stage. The loss decreased to around 0.7X at 0.02, but it suddenly spiked to over 20. After some time, it gradually decreased to around 6.x. Is this normal? And why did this happen? ![image](https://private-user-images.githubusercontent.com/35927125/292370534-00d978be-1fbd-45b8-add5-3c7ced9ce750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1MzQtMDBkOTc4YmUtMWZiZC00NWI4LWFkZDUtM2M3Y2VkOWNlNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzJlYjJmZmVlMDdlNjI1ZTYyMDUzYTBkZThjNjMwMmU5YWQ1ZmJlZWI5NDU2YjU2YzFmZTQ0YzJjNWNlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tulX8K3axjDw6HZoxohIaN3uhhI6AUvEWbgrCiXWeCk)
> > <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/35927125/292370566-f2b43797-23e5-4686-85bf-80ec23c225bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1NjYtZjJiNDM3OTctMjNlNS00Njg2LTg1YmYtODBlYzIzYzIyNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTg5YjRjOTg5YjM4MmU4ZjQ0MjIwYTgxMDVlZmQxZGYzNzU2N2QzOThkZDZlYmM1Njk1NDk3MWYxZWE4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNo08aV6fyVa8gkaskBNRs9rK1POfvgKnTWUaKKCsCk">
> 
> It is so wired. Could you provide your training script? Have you modified any training code?

Shure，I just follow the LLaVa1.5.

```
PROMPT_VERSION=plain
deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path ./checkpoints/$MODEL_VERSION \
    --version $PROMPT_VERSION \
    --data_path /path/to/pretrain_data.json \
    --image_folder /path/to/images \
    --vision_tower openai/clip-vit-large-patch14 \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-$MODEL_VERSION-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```
  And I note that the learning rate and batch size are not the same as yours. I will fix that and tell you later.

**Comment by xiaoachen98** [comment]
> > > Hi! Thanks for the great work! I encountered an issue during the pretraining stage. I was fine-tuning the vision tower, the linear adapter, and the Large Language Model (LLM) in the pretraining stage. The loss decreased to around 0.7X at 0.02, but it suddenly spiked to over 20. After some time, it gradually decreased to around 6.x. Is this normal? And why did this happen? ![image](https://private-user-images.githubusercontent.com/35927125/292370534-00d978be-1fbd-45b8-add5-3c7ced9ce750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1MzQtMDBkOTc4YmUtMWZiZC00NWI4LWFkZDUtM2M3Y2VkOWNlNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzJlYjJmZmVlMDdlNjI1ZTYyMDUzYTBkZThjNjMwMmU5YWQ1ZmJlZWI5NDU2YjU2YzFmZTQ0YzJjNWNlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tulX8K3axjDw6HZoxohIaN3uhhI6AUvEWbgrCiXWeCk)
> > > <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/35927125/292370566-f2b43797-23e5-4686-85bf-80ec23c225bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1NjYtZjJiNDM3OTctMjNlNS00Njg2LTg1YmYtODBlYzIzYzIyNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTg5YjRjOTg5YjM4MmU4ZjQ0MjIwYTgxMDVlZmQxZGYzNzU2N2QzOThkZDZlYmM1Njk1NDk3MWYxZWE4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNo08aV6fyVa8gkaskBNRs9rK1POfvgKnTWUaKKCsCk">
> > 
> > 
> > It is so wired. Could you provide your training script? Have you modified any training code?
> 
> Sure，I just follow the LLaVa1.5.
> 
> ```
> PROMPT_VERSION=plain
> deepspeed llava/train/train_mem.py \
>     --deepspeed ./scripts/zero2.json \
>     --model_name_or_path ./checkpoints/$MODEL_VERSION \
>     --version $PROMPT_VERSION \
>     --data_path /path/to/pretrain_data.json \
>     --image_folder /path/to/images \
>     --vision_tower openai/clip-vit-large-patch14 \
>     --tune_mm_mlp_adapter True \
>     --mm_vision_select_layer -2 \
>     --mm_use_im_start_end False \
>     --mm_use_im_patch_token False \
>     --bf16 True \
>     --output_dir ./checkpoints/llava-$MODEL_VERSION-pretrain \
>     --num_train_epochs 1 \
>     --per_device_train_batch_size 16 \
>     --per_device_eval_batch_size 4 \
>     --gradient_accumulation_steps 1 \
>     --evaluation_strategy "no" \
>     --save_strategy "steps" \
>     --save_steps 24000 \
>     --save_total_limit 1 \
>     --learning_rate 1e-3 \
>     --weight_decay 0. \
>     --warmup_ratio 0.03 \
>     --lr_scheduler_type "cosine" \
>     --logging_steps 1 \
>     --tf32 True \
>     --model_max_length 2048 \
>     --gradient_checkpointing True \
>     --dataloader_num_workers 4 \
>     --lazy_preprocess True \
>     --report_to wandb
> ```
> 
> And I note that the learning rate and batch size are not the same as yours. I will fix that and tell you later. My modifications to the training code did not influence the results with the llava dataset.

I found you close this issue. Did you solve it?

**Comment by yiyexy** [comment]
> > > > Hi! Thanks for the great work! I encountered an issue during the pretraining stage. I was fine-tuning the vision tower, the linear adapter, and the Large Language Model (LLM) in the pretraining stage. The loss decreased to around 0.7X at 0.02, but it suddenly spiked to over 20. After some time, it gradually decreased to around 6.x. Is this normal? And why did this happen? ![image](https://private-user-images.githubusercontent.com/35927125/292370534-00d978be-1fbd-45b8-add5-3c7ced9ce750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1MzQtMDBkOTc4YmUtMWZiZC00NWI4LWFkZDUtM2M3Y2VkOWNlNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzJlYjJmZmVlMDdlNjI1ZTYyMDUzYTBkZThjNjMwMmU5YWQ1ZmJlZWI5NDU2YjU2YzFmZTQ0YzJjNWNlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tulX8K3axjDw6HZoxohIaN3uhhI6AUvEWbgrCiXWeCk)
> > > > <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/35927125/292370566-f2b43797-23e5-4686-85bf-80ec23c225bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDE5NjEsIm5iZiI6MTcwMzI0MTY2MSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1NjYtZjJiNDM3OTctMjNlNS00Njg2LTg1YmYtODBlYzIzYzIyNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTg5YjRjOTg5YjM4MmU4ZjQ0MjIwYTgxMDVlZmQxZGYzNzU2N2QzOThkZDZlYmM1Njk1NDk3MWYxZWE4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNo08aV6fyVa8gkaskBNRs9rK1POfvgKnTWUaKKCsCk">
> > > 
> > > 
> > > It is so wired. Could you provide your training script? Have you modified any training code?
> > 
> > 
> > Sure，I just follow the LLaVa1.5.
> > ```
> > PROMPT_VERSION=plain
> > deepspeed llava/train/train_mem.py \
> >     --deepspeed ./scripts/zero2.json \
> >     --model_name_or_path ./checkpoints/$MODEL_VERSION \
> >     --version $PROMPT_VERSION \
> >     --data_path /path/to/pretrain_data.json \
> >     --image_folder /path/to/images \
> >     --vision_tower openai/clip-vit-large-patch14 \
> >     --tune_mm_mlp_adapter True \
> >     --mm_vision_select_layer -2 \
> >     --mm_use_im_start_end False \
> >     --mm_use_im_patch_token False \
> >     --bf16 True \
> >     --output_dir ./checkpoints/llava-$MODEL_VERSION-pretrain \
> >     --num_train_epochs 1 \
> >     --per_device_train_batch_size 16 \
> >     --per_device_eval_batch_size 4 \
> >     --gradient_accumulation_steps 1 \
> >     --evaluation_strategy "no" \
> >     --save_strategy "steps" \
> >     --save_steps 24000 \
> >     --save_total_limit 1 \
> >     --learning_rate 1e-3 \
> >     --weight_decay 0. \
> >     --warmup_ratio 0.03 \
> >     --lr_scheduler_type "cosine" \
> >     --logging_steps 1 \
> >     --tf32 True \
> >     --model_max_length 2048 \
> >     --gradient_checkpointing True \
> >     --dataloader_num_workers 4 \
> >     --lazy_preprocess True \
> >     --report_to wandb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I note that the learning rate and batch size are not the same as yours. I will fix that and tell you later. My modifications to the training code did not influence the results with the llava dataset.
> 
> I found you close this issue. Did you solve it?

I changed the learning rate from 1e-3 to 2e-5, which is same as yours, and trained the vision encoder in the last half of the architecture during the pre-training stage. Finally, the loss continued to decrease to the 0.2x range.

However, I can't explain this issue, and ultimately, my results are not better than those from LLaMA1.5 based on your dataset and using the LLaMA1.5 code. Perhaps there are some other aspects that I haven't considered.

**Comment by futureisatyourhand** [comment]
> Hi! Thanks for the great work! I encountered an issue during the pretraining stage. I was fine-tuning the vision tower, the linear adapter, and the Large Language Model (LLM) in the pretraining stage. The loss decreased to around 0.7X at 0.02, but it suddenly spiked to over 20. After some time, it gradually decreased to around 6.x. Is this normal? And why did this happen? ![image](https://private-user-images.githubusercontent.com/35927125/292370534-00d978be-1fbd-45b8-add5-3c7ced9ce750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDMyMjksIm5iZiI6MTcxMDI0MjkyOSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1MzQtMDBkOTc4YmUtMWZiZC00NWI4LWFkZDUtM2M3Y2VkOWNlNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3Zjc4MzgxZDA5YzIzZTFiMzU2ZWRhODQyODdhZDVmMzM0OTBhN2UzYTBlYmZmNDUyMjRhOTAzMTFkOWI2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-35i56fdKf3PSKW23eyUCnVBiypMdeIeNLj7c4NGX8Q)
> 
> <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/35927125/292370566-f2b43797-23e5-4686-85bf-80ec23c225bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDMyMjksIm5iZiI6MTcxMDI0MjkyOSwicGF0aCI6Ii8zNTkyNzEyNS8yOTIzNzA1NjYtZjJiNDM3OTctMjNlNS00Njg2LTg1YmYtODBlYzIzYzIyNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MGM5NTY4MWM4NGNiMmYxZWEwYmU3MjFkNDc5MmM2MTRmOGIzY2U5ZTFkYTY3YWQyZTdiNTc5Y2Q4ZGVlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fbaZg8tnTUX21uTtD7kTxqYlfbPKAZ_nguLgDrxjsXk">

hello,can you tell your resolvent？ thanks
