### ISSUE TITLE
「Share GPT4V」关于数据和论文对不起来的问题

### ISSUE THREAD

**Issue by shipengai** [InternLM/InternLM-XComposer#107]
在论文中提到“we replaced a corresponding portion of detailed cap- tions in their Supervised Fine-Tuning (SFT) datasets with a selection from our 100K GPT4-Vision-generated captions, 
while maintaining image data sources as consistent as possible”

这里替换的图片是llava中产生的23Kdetail数据吗？
我们发现在sharegpt4v_instruct_gpt4-vision_cap100k.json只能发现9599个对应的数据，少一半

**Comment by xiaoachen98** [comment]
> 在论文中提到“we replaced a corresponding portion of detailed cap- tions in their Supervised Fine-Tuning (SFT) datasets with a selection from our 100K GPT4-Vision-generated captions, while maintaining image data sources as consistent as possible”
> 
> 这里替换的图片是llava中产生的23Kdetail数据吗？ 我们发现在sharegpt4v_instruct_gpt4-vision_cap100k.json只能发现9599个对应的数据，少一半

We utilized the first 23K images (just ranked by names) contained in the COCO-train-2017 dataset too.
