### ISSUE TITLE
Minimum GPU memory to run example_chat.py

### ISSUE THREAD

**Issue by x1ngzai** [InternLM/InternLM-XComposer#11]
Hello, I am interested in your work and curious about the minimum total GPU memory required to run example_chat.py for testing. I tried it on mine, which has 8GB of memory, clearly not enough. Can you show me the rough range for it?

**Comment by LightDXY** [comment]
hi, thanks for your attention, the current model is 16-bit model, so 8G is not enough for it. We are preparing the 4-bit quantized model for light-weight usage.

**Comment by WeiXuanLi-1024** [comment]
> hi, thanks for your attention, the current model is 16-bit model, so 8G is not enough for it. We are preparing the 4-bit quantized model for light-weight usage.

我用的单卡24G显存的也跑不起来，这种7B VL模型的需要这么大的显存吗？

**Comment by zhaoxin111** [comment]
So what is the minimum GPU memory required to run it? Can it be run with multiple 3090 GPUs?

**Comment by WeiXuanLi-1024** [comment]
> So what is the minimum GPU memory required to run it? Can it be run with multiple 3090 GPUs?
![f1b22b0682b6522ae790a7a55040632](https://github.com/InternLM/InternLM-XComposer/assets/24350444/6f4acbd9-c059-4f2a-ac34-c97ecffe8edb)
应该需要32G显存

**Comment by yitong227** [comment]
请问下，多卡3090怎么部署？

**Comment by 18793658304** [comment]
> 请问下，多卡3090怎么部署？

同问

**Comment by myownskyW7** [comment]
The 4-bit version is released https://github.com/InternLM/InternLM-XComposer/commit/844084264e6abd9680679201384eb454692d3e96. It can be run on a GPU with >= 12GB memory.
