### ISSUE TITLE
 Is the inference speed  related to the resolution of the image？

### ISSUE THREAD

**Issue by MingyuLau** [InternLM/InternLM-XComposer#114]
I'm trying to label a batch of images using ShareGPT-4V, and I wonder if the model's inference speed is related to the image resolution size. If it is related, I will preprocess the images. If not, does a higher resolution result in better recognition? Also, I'm curious if there's a way to have the model process multiple images at once?

**Comment by xiaoachen98** [comment]
> I'm trying to label a batch of images using ShareGPT-4V, and I wonder if the model's inference speed is related to the image resolution size. If it is related, I will preprocess the images. If not, does a higher resolution result in better recognition? Also, I'm curious if there's a way to have the model process multiple images at once?

No. Your images will be resized to a fixed resolution of 336*336, which is consistent with the training process.
