### ISSUE TITLE
unable to reproduce the MME result

### ISSUE THREAD

**Issue by vanpersie32** [InternLM/InternLM-XComposer#116]
I cannot find the scrip get_images.py proposed in https://github.com/InternLM/InternLM-XComposer/blob/main/evaluation/mme/MME_Bench.md.

**Comment by myownskyW7** [comment]
@vanpersie32 We have released the InternLM-XComposer2-VL-7B, which is much more powerful. Please check the evaluation code here https://github.com/InternLM/InternLM-XComposer/tree/main/evaluation
