### ISSUE TITLE
About Run ShareCaptioner on the Local Server

### ISSUE THREAD

**Issue by ykj467422034** [InternLM/InternLM-XComposer#117]
Hello, can I ask a question that how to run share-cap_batch_infer.py on the local server? I have downloaded "Lin-Chen/ShareCaptioner" to the server on huggingface. @xiaoachen98

**Comment by ykj467422034** [comment]
@xiaoachen98

**Comment by xiaoachen98** [comment]
> Hello, can I ask a question that how to run share-cap_batch_infer.py on the local server? I have downloaded "Lin-Chen/ShareCaptioner" to the server on huggingface. @xiaoachen98

You just have to prepare a JSON file composed of the path of your images and run share-cap_batch_infer.py directly.

**Comment by ykj467422034** [comment]
OK，thank you very much.
