### ISSUE TITLE
how can i install `rotary_emb` ?

### ISSUE THREAD

**Issue by itiwtbb** [InternLM/InternLM-XComposer#12]
>>> from transformers import AutoModel, AutoTokenizer
>>> model = AutoModel.from_pretrained('/root/autodl-tmp/models/internlm7bxc', trust_remote_code=True).cuda().eval()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/llm_chat/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 550, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/root/miniconda3/envs/llm_chat/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 497, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/root/miniconda3/envs/llm_chat/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 199, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/root/miniconda3/envs/llm_chat/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/huggingface/modules/transformers_modules/internlm7bxc/modeling_InternLM_XComposer.py", line 18, in <module>
    from .modeling_InternLM import *
  File "/root/.cache/huggingface/modules/transformers_modules/internlm7bxc/modeling_InternLM.py", line 5, in <module>
    import rotary_emb

**Comment by LightDXY** [comment]
The rotary_emb is installed with the flash-attention, please refer to the [installation instructions](https://github.com/InternLM/InternLM-XComposer/blob/main/docs/install.md) for more detail

**Comment by myownskyW7** [comment]
The rotary_emb is not required in the updated Huggingface and Modelscope models. Please download the new Huggingface / Modelscope models and try the latest version.

**Comment by waltonfuture** [comment]
> The rotary_emb is not required in the updated Huggingface and Modelscope models. Please download the new Huggingface / Modelscope models and try the latest version.

In the newest 4-bit version, this problem still exists

**Comment by rayquazaMega** [comment]
Maybe we just need the function rotary_emb.apply_rotary.
Copied from [ShareCaptioner](https://huggingface.co/Lin-Chen/ShareCaptioner/resolve/main/modeling_InternLM.py?download=true):
```
def rotary_embed(x1, x2, cos, sin, conj):
    x1, x2 = x1.float(), x2.float()
    if conj:
        x1, x2 = x1 * cos + x2 * sin, x1 * sin + x2 * cos
    else:
        x1, x2 = x1 * cos - x2 * sin, x1 * sin + x2 * cos
    return x1, x2


class LegacyApplyRotaryEmbQKV_(torch.autograd.Function):

    @staticmethod
    def forward(ctx, qkv, cos, sin, cos_k=None, sin_k=None, interleaved=False):
        """
            qkv: (batch_size, seqlen, 3, nheads, headdim)
            cos, sin: (seqlen, rotary_dim / 2)
            cos_k, sin_k: (seqlen, rotary_dim / 2), optional
            interleaved: if True, rotate pairs of even and odd dimensions (GPT-J style) instead of
                1st half and 2nd half (GPT-NeoX style).
        rotary_dim must be <= headdim
        Apply rotary embedding *inplace* to the first rotary_dim of q and k.
        """
        batch, seqlen, three, nheads, headdim = qkv.shape
        assert three == 3
        rotary_seqlen, rotary_dim = cos.shape
        rotary_dim *= 2
        assert rotary_dim <= headdim
        assert seqlen <= rotary_seqlen
        cos_k = cos if cos_k is None else cos_k
        sin_k = sin if sin_k is None else sin_k
        assert sin.shape == cos_k.shape == sin_k.shape == (rotary_seqlen, rotary_dim // 2)
        q_ro = qkv[:, :, 0, :, :rotary_dim]
        q1, q2 = q_ro.chunk(2, dim=-1) if not interleaved else (q_ro[..., ::2], q_ro[..., 1::2])
        # rotary_emb.apply_rotary(q1, q2, rearrange(cos[:seqlen], 's d -> s 1 d'),
        #                         rearrange(sin[:seqlen], 's d -> s 1 d'), q1, q2, False)
        q1, q2 = rotary_embed(q1, q2, rearrange(cos[:seqlen], 's d -> s 1 d'), rearrange(sin[:seqlen], 's d -> s 1 d'), False)
        qkv[:, :, 0, :, :rotary_dim] = torch.cat([q1, q2], dim=-1)
        k_ro = qkv[:, :, 1, :, :rotary_dim]
        k1, k2 = k_ro.chunk(2, dim=-1) if not interleaved else (k_ro[..., ::2], k_ro[..., 1::2])
        # rotary_emb.apply_rotary(k1, k2, rearrange(cos_k[:seqlen], 's d -> s 1 d'),
        #                         rearrange(sin_k[:seqlen], 's d -> s 1 d'), k1, k2, False)
        k1, k2 = rotary_embed(k1, k2, rearrange(cos_k[:seqlen], 's d -> s 1 d'), rearrange(sin_k[:seqlen], 's d -> s 1 d'), False)
        qkv[:, :, 1, :, :rotary_dim] = torch.cat([k1, k2], dim=-1)
        ctx.save_for_backward(cos, sin, cos_k, sin_k)
        ctx.interleaved = interleaved
        return qkv
```
