### ISSUE TITLE
internlm-xcomposer-vl-7b推理，为什么输出倾向于英文呢？

### ISSUE THREAD

**Issue by LianghuiGuo** [InternLM/InternLM-XComposer#121]
instruct是中文的，例如：“图中有可口可乐吗”，单模型倾向于输出英文，大概80%的输出是英文。

**Comment by myownskyW7** [comment]
这个主要是训练数据英文占比大导致的，一个直接的解决方案是问“图中有可口可乐吗，用中文回答”。另外，我们最近开源了InternLM-XComposer2, 比之前的1.0要强大的多，建议直接用2.0。https://github.com/InternLM/InternLM-XComposer?tab=readme-ov-file#model-zoo

**Comment by sunjunlishi** [comment]
![1711940734704](https://github.com/InternLM/InternLM-XComposer/assets/11845664/8177580c-1d95-418f-b16b-31a3a6e8286f)
提示了，还是用的英文回答
