### ISSUE TITLE
Could you provide the necessary pictures for the training?

### ISSUE THREAD

**Issue by Eric-is-good** [InternLM/InternLM-XComposer#122]
![image](https://github.com/InternLM/InternLM-XComposer/assets/73528862/b91c9db3-52df-4361-b50e-91919c8e824c)
I am reading your paper ”sharegpt4v"

I would like to reproduce your work and therefore need the dataset images corresponding to your paper. Could you please provide datasets that are not included in the dataset used in llava, such as LCS, SAM, TextCaps, WikiArt, and web-crawled data that you used? You just only used a small portion of them, it is not cost-effective to download them all.

Thank you.

**Comment by xiaoachen98** [comment]
> ![image](https://private-user-images.githubusercontent.com/73528862/296504930-b91c9db3-52df-4361-b50e-91919c8e824c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzYxMzMsIm5iZiI6MTcwNTM3NTgzMywicGF0aCI6Ii83MzUyODg2Mi8yOTY1MDQ5MzAtYjkxYzlkYjMtNTJkZi00MzYxLWI1MGUtOTE5MTljOGU4MjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZTk5OWU5NDBmMWU0YTIxNzMyMDI4ZDMyY2JiMmUxYzk2M2E0MGIxN2JjOTJlMGI2ZmIwNTEzMzA1YzdkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrvm9iGxlsOi3GvNWHY9yR1_8pvG0nyqyAWIkFX9NqA) I am reading your paper ”sharegpt4v"
> 
> I would like to reproduce your work and therefore need the dataset images corresponding to your paper. Could you please provide datasets that are not included in the dataset used in llava, such as LCS, SAM, TextCaps, WikiArt, and web-crawled data that you used? You just only used a small portion of them, it is not cost-effective to download them all.
> 
> Thank you.

The LCS dataset you can download according to the LLaVA guidelines. For the SAM dataset, we only used the first 0-50 parquet, and for TextCaps, WikiArt, and web-crawled data we have provided a [subset](https://drive.google.com/drive/folders/1tCUQ-sq6vdshZVkF0ZeF3K4eztkXJgax?usp=sharing) of the data used.

**Comment by Eric-is-good** [comment]
> > ![image](https://private-user-images.githubusercontent.com/73528862/296504930-b91c9db3-52df-4361-b50e-91919c8e824c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzYxMzMsIm5iZiI6MTcwNTM3NTgzMywicGF0aCI6Ii83MzUyODg2Mi8yOTY1MDQ5MzAtYjkxYzlkYjMtNTJkZi00MzYxLWI1MGUtOTE5MTljOGU4MjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZTk5OWU5NDBmMWU0YTIxNzMyMDI4ZDMyY2JiMmUxYzk2M2E0MGIxN2JjOTJlMGI2ZmIwNTEzMzA1YzdkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrvm9iGxlsOi3GvNWHY9yR1_8pvG0nyqyAWIkFX9NqA) I am reading your paper ”sharegpt4v"
> > I would like to reproduce your work and therefore need the dataset images corresponding to your paper. Could you please provide datasets that are not included in the dataset used in llava, such as LCS, SAM, TextCaps, WikiArt, and web-crawled data that you used? You just only used a small portion of them, it is not cost-effective to download them all.
> > Thank you.
> 
> The LCS dataset you can download according to the LLaVA guidelines. For the SAM dataset, we only used the first 0-50 parquet, and for TextCaps, WikiArt, and web-crawled data we have provided a [subset](https://drive.google.com/drive/folders/1tCUQ-sq6vdshZVkF0ZeF3K4eztkXJgax?usp=sharing) of the data used.

Thank you very much !!
