### ISSUE TITLE
针对低分辨率，很模糊的图像，是否可以获得较高质量的文本描述？

### ISSUE THREAD

**Issue by shams2023** [InternLM/InternLM-XComposer#123]
目前图像分辨率较低（60*128）左右，并且图像质量很差，是都可以通过这个model获得较高质量的文本描述？

**Comment by xiaoachen98** [comment]
> 目前图像分辨率较低（60*128）左右，并且图像质量很差，是都可以通过这个model获得较高质量的文本描述？

The resolution we've been using is 336x336, you can try to see how the model behaves at 60x128 resolution. Our image processor will scale the image to 336x336 first. looking forward to your feedback when you try it.

**Comment by shams2023** [comment]
> > 目前图像分辨率较低（60*128）左右，并且图像质量很差，是都可以通过这个model获得较高质量的文本描述？
> 
> The resolution we've been using is 336x336, you can try to see how the model behaves at 60x128 resolution. Our image processor will scale the image to 336x336 first. looking forward to your feedback when you try it.

![image](https://github.com/InternLM/InternLM-XComposer/assets/141383792/c352b64f-222f-4841-ad42-60ecd7e26400)
这是针对低分辨率图像获得的文本描述，我并不想获得如此宽泛的文本描述，而是希望得到具有细节描述的文本（比如穿着什么样的毛衣的男人（带有什么什么图案的毛衣）类似于这种针对图像细节的描述），请问需要做些什么可以获得这种描述呢？

**Comment by xiaoachen98** [comment]
> > > 目前图像分辨率较低（60*128）左右，并且图像质量很差，是都可以通过这个model获得较高质量的文本描述？
> > 
> > 
> > The resolution we've been using is 336x336, you can try to see how the model behaves at 60x128 resolution. Our image processor will scale the image to 336x336 first. looking forward to your feedback when you try it.
> 
> ![image](https://private-user-images.githubusercontent.com/141383792/296988572-c352b64f-222f-4841-ad42-60ecd7e26400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjM3NTgsIm5iZiI6MTcwNTQ2MzQ1OCwicGF0aCI6Ii8xNDEzODM3OTIvMjk2OTg4NTcyLWMzNTJiNjRmLTIyMmYtNDg0MS1hZDQyLTYwZWNkN2UyNjQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMzUwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWMwOGVjODQwMWVjYTg4YzEwNTQ0ZWE1ODdhN2Q4NzEwMTkyNjhmOWEwYTRkZDgwYWMwMTYxYWNmYmQyNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1YcD7J05SAsncbZzf_LPbxv1WCRSwWOejOKIPDl4QCg) ![image](https://private-user-images.githubusercontent.com/141383792/296989840-4aee8e56-3ca1-4430-bf6f-e5706f7e836a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjM3NTgsIm5iZiI6MTcwNTQ2MzQ1OCwicGF0aCI6Ii8xNDEzODM3OTIvMjk2OTg5ODQwLTRhZWU4ZTU2LTNjYTEtNDQzMC1iZjZmLWU1NzA2ZjdlODM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMzUwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2MzNzhhZThiNDExZjJlNDFjMzYyOWE0ZTVlZDFlNjNmN2NhYTAwOTEzMzc1NTM1YTNlOTU4NzVjYjUxMzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aCLXnNGZ5DB8W0PQgb4fNhmU-JQt_qv-3-QPIi1dWpA)
> 
> 这是针对低分辨率图像获得的文本描述，我并不想获得如此宽泛的文本描述，而是希望得到具有细节描述的文本（比如穿着什么样的毛衣的男人（带有什么什么图案的毛衣）类似于这种针对图像细节的描述。其次，我还不希望模型有自己的想法，他总是会自己臆想一些东西，其实图像中是不包含这种东西的。最后，对于背景的描述我其实是可有可无的，最好还是集中描述图像中行人本身），请问需要做些什么可以获得这种描述呢？

Maybe you can try to use the ShareGPT4V-7B model and write a proper prompt, since this ShareCaptioner is not very capable of instruction-following.

**Comment by shams2023** [comment]
> > > > 目前图像分辨率较低（60*128）左右，并且图像质量很差，是都可以通过这个模型获得较高质量的文本描述？
> > > 
> > > 
> > > 我们一直使用的分辨率是 336x336，您可以尝试查看模型在 60x128 分辨率下的表现。我们的图像处理器将首先将图像缩放到 336x336。期待您在尝试时的反馈。
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/141383792/296988572-c352b64f-222f-4841-ad42-60ecd7e26400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjM3NTgsIm5iZiI6MTcwNTQ2MzQ1OCwicGF0aCI6Ii8xNDEzODM3OTIvMjk2OTg4NTcyLWMzNTJiNjRmLTIyMmYtNDg0MS1hZDQyLTYwZWNkN2UyNjQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMzUwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWMwOGVjODQwMWVjYTg4YzEwNTQ0ZWE1ODdhN2Q4NzEwMTkyNjhmOWEwYTRkZDgwYWMwMTYxYWNmYmQyNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1YcD7J05SAsncbZzf_LPbxv1WCRSwWOejOKIPDl4QCg) ![图像](https://private-user-images.githubusercontent.com/141383792/296989840-4aee8e56-3ca1-4430-bf6f-e5706f7e836a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjM3NTgsIm5iZiI6MTcwNTQ2MzQ1OCwicGF0aCI6Ii8xNDEzODM3OTIvMjk2OTg5ODQwLTRhZWU4ZTU2LTNjYTEtNDQzMC1iZjZmLWU1NzA2ZjdlODM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMzUwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2MzNzhhZThiNDExZjJlNDFjMzYyOWE0ZTVlZDFlNjNmN2NhYTAwOTEzMzc1NTM1YTNlOTU4NzVjYjUxMzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aCLXnNGZ5DB8W0PQgb4fNhmU-JQt_qv-3-QPIi1dWpA)
> > 这是针对低分辨率图像获得的文本描述，我并不想获得如此宽泛的文本描述，而是希望得到具有细节描述的文本（比如穿着什么样的毛衣的男人（带有什么什么图案的毛衣）类似于这种针对图像细节的描述。其次，我还不希望模型有自己的想法，他总是会自己臆想一些东西，其实图像中是不包含这种东西的。最后，对于背景的描述我其实是可有可无的，最好还是集中描述图像中行人本身），请问需要做些什么可以获得这种描述呢？
> 
> 也许您可以尝试使用 ShareGPT4V-7B 模型并编写适当的提示，因为这个 ShareCaptioner 的指令遵循能力不强。

我目前就在使用ShareGPT4V-7B，我确实发现 ShareCaptioner 生成的文本远没有ShareGPT4V-7B生成的文本质量高
