### ISSUE TITLE
About SAM data

### ISSUE THREAD

**Issue by becauseofAI** [InternLM/InternLM-XComposer#127]
Can you explain the inclusion relationship between ```cap23k``` and ```sam9k``` in file [sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json)?

Also, can you also provide a separate copy of SAM data included in file  [sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json)? Because the SAM data is too large, even for the 000000~000050.tar used in your paper.

**Comment by xiaoachen98** [comment]
> Can you explain the inclusion relationship between `cap23k` and `sam9k` in file [sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json)?
> 
> Also, can you also provide a separate copy of SAM data included in file [sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json)? Because the SAM data is too large, even for the 000000~000050.tar used in your paper.

Thanks for your feedback. We have already uploaded sam9k images. You can download it following [this doc](https://github.com/InternLM/InternLM-XComposer/blob/main/projects/ShareGPT4V/docs/Data.md)
