### ISSUE TITLE
图文问答模型是用InternLM-XComposer-VL-7B还是InternLM-XComposer-7B？

### ISSUE THREAD

**Issue by xyfZzz** [InternLM/InternLM-XComposer#128]

**Comment by myownskyW7** [comment]
@xyfZzz 图文问答用InternLM-XComposer-VL-7B，我们现在已经开源了2.0版本，图文问答性能比1.0高的多，建议直接用InternLM-XComposer2-VL-7B

**Comment by shams2023** [comment]
> 建议直接用InternLM-XComposer2-VL-7B做图文

请问你成功了吗？图文问答
