### ISSUE TITLE
最新的web_demo.py又复现了之前无法自动插图的bug？

### ISSUE THREAD

**Issue by ZhuangPeiyu** [InternLM/InternLM-XComposer#131]
如题，之前的这个bug貌似在去年10月就修复了https://github.com/InternLM/InternLM-XComposer/issues/35，https://github.com/InternLM/InternLM-XComposer/issues/26，我下载最新的代码（20240106）发现创作图文并茂的文章的时候还是出现图片无法正常插入的问题。

**Comment by myownskyW7** [comment]
@ZhuangPeiyu Please try our InternLM-XComposer2, it is much better.
