### ISSUE TITLE
video update

### ISSUE THREAD

**Issue by panzhang0212** [InternLM/InternLM-XComposer#132]
https://github.com/InternLM/InternLM-XComposer/assets/30363822/7c399c65-0cdd-41ae-a903-49b58dca609a

**Comment by panzhang0212** [comment]
https://github.com/InternLM/InternLM-XComposer/assets/30363822/63756590-7366-4c5d-807f-66c4e69ea827

**Comment by myownskyW7** [comment]
Uploading demo_en_10m.mp4…

**Comment by WillowBreeze** [comment]
https://github.com/InternLM/InternLM-XComposer/assets/147793160/70be926a-90ac-45f6-8b0a-5200dad1c7e4

**Comment by WillowBreeze** [comment]
https://github.com/InternLM/InternLM-XComposer/assets/147793160/8206f07f-3166-461e-a631-9cbcdec6ae75

**Comment by myownskyW7** [comment]
https://github.com/user-attachments/assets/c8a22fb1-c2da-4396-aca1-2148b7ac1952

**Comment by yhcao6** [comment]
https://github.com/user-attachments/assets/554dd7a5-de3d-4eb0-81a2-061745fa8d9a

**Comment by yhcao6** [comment]
https://github.com/user-attachments/assets/fd340f06-5586-452c-ae7b-59c983d4adcc
