### ISSUE TITLE
请问InternLM-XComposer2在DocVQA和TextVQA上的效果如何？

### ISSUE THREAD

**Issue by xyfZzz** [InternLM/InternLM-XComposer#135]
请问InternLM-XComposer2在DocVQA和TextVQA这类数据集上的效果如何？有测试过吗？

**Comment by yuhangzang** [comment]
We provide the high-resolution version model [4khd](https://arxiv.org/pdf/2404.06512) and [IXC 2.5](https://arxiv.org/html/2407.03320v1), which report the results on DocVQA and TextVQA.
