### ISSUE TITLE
InternLM-XComposer2 WeChat expired, Huggingface Demo 502 Bad Gateway

### ISSUE THREAD

**Issue by zixindh** [InternLM/InternLM-XComposer#136]

**Comment by myownskyW7** [comment]
Please try this OpenXLab Demo pls: https://openxlab.org.cn/apps/detail/WillowBreeze/InternLM-XComposer

**Comment by zixindh** [comment]
thanks, this one works

**Comment by ppeterpp** [comment]
> Please try this OpenXLab Demo pls: https://openxlab.org.cn/apps/detail/WillowBreeze/InternLM-XComposer

demo of share-captioner in huggingface also received 502 bad gateway, while demo of the same in OpenXLab is always 'starting' and also not usable, could you please help?
