### ISSUE TITLE
When will the code for training or fine-tuning version 2 be released?

### ISSUE THREAD

**Issue by xmc-andy** [InternLM/InternLM-XComposer#139]
When will the code for training or fine-tuning version 2 be released?

**Comment by Jintao-Huang** [comment]
`ms-swift` LLM training framework has incorporated sft for internlm-xcomposer2 ~ 😊

It provides example scripts and supports custom datasets. You can check it out here ~
https://github.com/modelscope/swift/tree/main/examples/pytorch/llm/scripts/internlm_xcomposer2_7b_chat

The script utilizes the COCO dataset for fine-tuning. After training, the generated samples are as follows:
```python
"""
[QUERY]Picture 1:<img>https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/val2014/COCO_val2014_000000492132.jpg</img>
please describe the image.
[OUTPUT] A large airplane hangs from the ceiling of a museum.[UNUSED_TOKEN_145]
[LABELS]People walking in a museum with a airplane hanging from the celing.
--------------------------------------------------------------------
[QUERY]Picture 1:<img>https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/val2014/COCO_val2014_000000558642.jpg</img>
please describe the image.
[OUTPUT] A bowl of fruit topped with a pastry and a spoon.[UNUSED_TOKEN_145]
[LABELS]a bowl of fruit and pastry on a table
"""
```

**Comment by xmc-andy** [comment]
Thanks for the answer and sharing, I will do further research.

**Comment by yuhangzang** [comment]
Our latest commit a377bd8  provides the finetuning code for XComposer2. Please refer to https://github.com/InternLM/InternLM-XComposer/tree/main/finetune

**Comment by xmc-andy** [comment]
> Our latest commit [a377bd8](https://github.com/InternLM/InternLM-XComposer/commit/a377bd86232c597499aa17e66b9ea7fcee9e8020) provides the finetuning code for XComposer2. Please refer to https://github.com/InternLM/InternLM-XComposer/tree/main/finetune

Got it！Thanks～

**Comment by YerongLi** [comment]
Does anyone can reproduce the SFT for now, I find this is buggy.
