### ISSUE TITLE
User warnings when loading model 

### ISSUE THREAD

**Issue by ceballots** [InternLM/InternLM-XComposer#142]
Hello,

when loading the `internlm/internlm-xcomposer2-7b` as stated in [here](https://huggingface.co/internlm/internlm-xcomposer2-7b) I get these warnings for each layer in the vision model `UserWarning: for vision_model.encoder.layers.1.layer_norm2.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?) warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '`

Thank you!

**Comment by myownskyW7** [comment]
@ceballots vision_model.encoder.layers.1.layer_norm2.bias is not used actually. Please just ignore this warning.
