### ISSUE TITLE
[ShareCaptioner] Multi-GPU inference

### ISSUE THREAD

**Issue by xiujiesong** [InternLM/InternLM-XComposer#144]
Hi,

Thanks for your great work. I am wondering is ShareCaptioner support multi-gpu inference? When I run share-cap_batch_infer.py, even though I set device_map="auto" it still just uses one GPU and i got a OutOfMemoryError.

**Comment by panzhang0212** [comment]
Thanks @wp1811983038 . Feel free to reopen this issue if you have any problems.
