### ISSUE TITLE
Run local demo for ShareGPT4V

### ISSUE THREAD

**Issue by zihui-debug** [InternLM/InternLM-XComposer#146]
Does this mean I need to install LLaVA repository?
```
Traceback (most recent call last):
  File "/InternLM-XComposer/projects/ShareGPT4V/tools/app.py", line 10, in <module>
    from llava.constants import (DEFAULT_IM_END_TOKEN, DEFAULT_IM_START_TOKEN,
ModuleNotFoundError: No module named 'llava'
(share4v) ***@ubuntu:~/InternLM-XComposer/projects/ShareGPT4V$ # run script
(share4v) ***@ubuntu:~/InternLM-XComposer/projects/ShareGPT4V$ python tools/app.py
Traceback (most recent call last):
  File "/InternLM-XComposer/projects/ShareGPT4V/tools/app.py", line 10, in <module>
    from llava.constants import (DEFAULT_IM_END_TOKEN, DEFAULT_IM_START_TOKEN,
ModuleNotFoundError: No module named 'llava'
```

**Comment by xiaoachen98** [comment]
> Does this mean I need to install LLaVA repository?
> 
> ```
> Traceback (most recent call last):
>   File "/InternLM-XComposer/projects/ShareGPT4V/tools/app.py", line 10, in <module>
>     from llava.constants import (DEFAULT_IM_END_TOKEN, DEFAULT_IM_START_TOKEN,
> ModuleNotFoundError: No module named 'llava'
> (share4v) ***@ubuntu:~/InternLM-XComposer/projects/ShareGPT4V$ # run script
> (share4v) ***@ubuntu:~/InternLM-XComposer/projects/ShareGPT4V$ python tools/app.py
> Traceback (most recent call last):
>   File "/InternLM-XComposer/projects/ShareGPT4V/tools/app.py", line 10, in <module>
>     from llava.constants import (DEFAULT_IM_END_TOKEN, DEFAULT_IM_START_TOKEN,
> ModuleNotFoundError: No module named 'llava'
> ```

Thanks for your feedback. We have already fixed that.
