### ISSUE TITLE
单张卡40g测试transformers和hug上的例子会out of mem

### ISSUE THREAD

**Issue by luyao-cv** [InternLM/InternLM-XComposer#150]

**Comment by myownskyW7** [comment]
@luyao-cv Don't worry. 4bit version for saving GPU memory is on the road.

**Comment by Asianfleet** [comment]
我在我的A100-40G上也遇到了同样的问题。我的解决办法是，将示例中的
model = AutoModel.from_pretrained('internlm/internlm-xcomposer2-vl-7b', trust_remote_code=True).cuda().eval()
改为
model = AutoModel.from_pretrained('internlm/internlm-xcomposer2-vl-7b', device_map='cuda', trust_remote_code=True).half().eval()
即可运行
