### ISSUE TITLE
请问如何基于InternLM-XComposer2训练lora？

### ISSUE THREAD

**Issue by bingwork** [InternLM/InternLM-XComposer#153]
可以直接使用https://github.com/InternLM/InternLM-XComposer/blob/main/InternLM-XComposer-1.0/finetune/finetune.py吗？感谢！
@myownskyW7 @LightDXY @eltociear @yhcao6 @vansin

**Comment by yuhangzang** [comment]
Our latest commit `a377bd8 ` provides the finetuning code for XComposer2. Please refer to https://github.com/InternLM/InternLM-XComposer/tree/main/finetune

**Comment by bingwork** [comment]
@yuhangzang, thank you very much for promptly replying to my message and quickly adding a pull request!

Upon examining the lora_target_modules, I noticed that some keys, such as 'mlp.up_proj', 'mlp.down_proj', 'mlp.gate_proj', and 'self_attn.o_proj', are no longer present in the model InternLMXComposer2ForCausalLM.

As I intend to fine-tune Plora_A and Plora_B, I would greatly appreciate any alternative suggestions you might have.

**Comment by yuhangzang** [comment]
Please try the recent commit `3c522e7` and see if the issue is fixed.

**Comment by myownskyW7** [comment]
@bingwork Please check the updated finetuning code.
