### ISSUE TITLE
Very Poor at Explaining in Korean Language

### ISSUE THREAD

**Issue by AbrahimZaman360** [InternLM/InternLM-XComposer#157]
How to improve it in Korean language for OCR and Text Generation?

**Comment by myownskyW7** [comment]
@AbrahimZaman360 I am sorry for this unsatisfactory experience. InternLM-XComposer2 is a bilingual Vision Language Model for English and Chinese. For a better experience with the Korean language, you may consider finetuning the model with Korean language OCR and text data.

**Comment by myownskyW7** [comment]
@AbrahimZaman360 Please check how to finetune this model at https://github.com/InternLM/InternLM-XComposer/tree/main/finetune

**Comment by AbrahimZaman360** [comment]
> @AbrahimZaman360 Please check how to finetune this model at https://github.com/InternLM/InternLM-XComposer/tree/main/finetune

Can I finetune KoLLAVA Dataset on InternLM-Xcomposer-2?

**Comment by shams2023** [comment]
> > @AbrahimZaman360请检查如何微调此模型：https://github.com/InternLM/InternLM-XComposer/tree/main/finetune
> 
> 我可以在 InternLM-Xcomposer-2 上微调 KoLLAVA 数据集吗？

Have you successfully fine tuned using your own dataset?

**Comment by AbrahimZaman360** [comment]
> > > @AbrahimZaman360请检查如何微调此模型：https://github.com/InternLM/InternLM-XComposer/tree/main/finetune
> > 
> > 我可以在 InternLM-Xcomposer-2 上微调 KoLLAVA 数据集吗？
> 
> Have you successfully fine tuned using your own dataset?
> 

Nope

**Comment by shams2023** [comment]
> > > > @AbrahimZaman360请检查如何微调此模型：https://github.com/InternLM/InternLM-XComposer/tree/main/finetune
> > > 
> > > 
> > > 我可以在 InternLM-Xcomposer-2 上微调 KoLLAVA 数据集吗？
> > 
> > 
> > 您是否使用自己的数据集成功进行了微调？
> 
> 不

me too
