### ISSUE TITLE
自定义数据 lora 微调InternLM-XComposer2-vl-7b后保存的权重推理效果与官方预训练权重一致，无法有效执行下游任务

### ISSUE THREAD

**Issue by lancerste** [InternLM/InternLM-XComposer#159]

**Comment by yuhangzang** [comment]
Please try the recent commit `3c522e7` and see if the issue is fixed.

**Comment by myownskyW7** [comment]
@lancerste Please check the updated finetuning code.

**Comment by iFe1er** [comment]
@lancerste 大佬这里有解决方案吗 @myownskyW7

**Comment by HoraceXIaoyiBao** [comment]
> 论是用lora微调后的几个epoch的权重表现无差异，且与官方预训练权重效果一致（无效lora微调）

请问解决了吗    训练的loss是0吗
