### ISSUE TITLE
Why the reponse generates the file name?

### ISSUE THREAD

**Issue by LinB203** [InternLM/InternLM-XComposer#165]
In sharegpt4v's pretrained json.

"value": "The image captures a close-up view of a stone wall, bathed in the soft glow of ambient light. The wall is adorned with ancient carvings, etched into the stone in a language that has long since faded into obscurity. The carvings are arranged in a grid-like pattern, each one a testament to the craftsmanship of a bygone era. \n\nThe carvings themselves are a mix of symbols and text, their meaning known only to those who understand the language they represent. Some of the carvings bear the marks of time, with moss and lichen clinging to the stone, adding a touch of green to the otherwise monochrome scene. \n\nThe perspective of the image is from the side of the wall, giving a sense of the wall's length and the density of the carvings. The background is shrouded in darkness, drawing the viewer's focus to the intricate details of the carvings. Despite the passage of time, the carvings stand resolute, a silent witness to the stories of the past. **\n\nAs for the landmark identification \"sa_17478\", I'm afraid I couldn't find any specific information related to this code in my current knowledge base. It might be a specific code or identifier used in a certain system or database. If you have more context or information about this code, I might be able to provide a more accurate response."**

I just wonder why the reponse generates the file name? The `sa_17478` is the file name.

**Comment by xiaoachen98** [comment]
> In sharegpt4v's pretrained json.
> 
> "value": "The image captures a close-up view of a stone wall, bathed in the soft glow of ambient light. The wall is adorned with ancient carvings, etched into the stone in a language that has long since faded into obscurity. The carvings are arranged in a grid-like pattern, each one a testament to the craftsmanship of a bygone era. \n\nThe carvings themselves are a mix of symbols and text, their meaning known only to those who understand the language they represent. Some of the carvings bear the marks of time, with moss and lichen clinging to the stone, adding a touch of green to the otherwise monochrome scene. \n\nThe perspective of the image is from the side of the wall, giving a sense of the wall's length and the density of the carvings. The background is shrouded in darkness, drawing the viewer's focus to the intricate details of the carvings. Despite the passage of time, the carvings stand resolute, a silent witness to the stories of the past. **\n\nAs for the landmark identification "sa_17478", I'm afraid I couldn't find any specific information related to this code in my current knowledge base. It might be a specific code or identifier used in a certain system or database. If you have more context or information about this code, I might be able to provide a more accurate response."**
> 
> I just wonder why the reponse generates the file name? The `sa_17478` is the file name.

We apologize for this mistake. As mentioned in our paper, we integrate the landmark information in the prompt to instruct GPT4V to recognize the location better. However, a very small portion of the SAM data incorrectly uses the landmark's prompt and creates this problem. We will fix this soon and update the json file. We apologize for the inconvenience.

**Comment by zodiacg** [comment]
Seems the problem still exists?
