### ISSUE TITLE
不可以单独生成图片吗？

### ISSUE THREAD

**Issue by ArlanCooper** [InternLM/InternLM-XComposer#17]
我这边调用的是internlm-xcomposer-7b的模型，然后输入如下命令：
```
>>> text='请帮我画一张长城的照片'
>>> response, history = model.chat(text=text, image=None, history=None)
>>> print(response)
很抱歉，作为一个语言模型，我并不具备绘画能力，无法为您画一张长城的照片。但是，如果您愿意，我可以为您提供一些关于长城的资料和信息，帮助您更好地了解这座伟大的建筑。
>>>
```

他是只能生成图文并茂的文章吗？

**Comment by myownskyW7** [comment]
我们的模型可以给文章配图，图片来自我们提供的题库，而不是生成图片。我们后面会支持给文字内容配图的对话。

Our model can add images to articles, with images coming from our provided image gallery, rather than generating images. We will support dialogues that pair text content with images in the future.

**Comment by ArlanCooper** [comment]
> 我们的模型可以给文章配图，图片来自我们提供的题库，而不是生成图片。我们后面会支持给文字内容配图的对话。
> 
> Our model can add images to articles, with images coming from our provided image gallery, rather than generating images. We will support dialogues that pair text content with images in the future.

嗷嗷，好滴，明白了，谢谢，那这个图库我们客户以自己扩展吗？

**Comment by lucasjinreal** [comment]
图库类似于embedding 检索？

**Comment by MrRace** [comment]
@myownskyW7 所以，只能在WebUI上点击"search"按钮，然后去图库进行检索？

**Comment by myownskyW7** [comment]
> > 我们的模型可以给文章配图，图片来自我们提供的题库，而不是生成图片。我们后面会支持给文字内容配图的对话。
> > Our model can add images to articles, with images coming from our provided image gallery, rather than generating images. We will support dialogues that pair text content with images in the future.
> 
> 嗷嗷，好滴，明白了，谢谢，那这个图库我们客户以自己扩展吗？

这个目前可以通过自己改代码来修改，我们后面会考虑增加一个用户换自己图库的功能。

**Comment by myownskyW7** [comment]
> 图库类似于embedding 检索？

现在选图是两个步骤，第一步是embedding检索，第二步多模态模型会从选出来的图里面再挑一张最合适的。不过只用第一步也能得到还不错的效果。

**Comment by myownskyW7** [comment]
> @myownskyW7 所以，只能在WebUI上点击"search"按钮，然后去图库进行检索？

这是一个临时可用的解决方案。
