### ISSUE TITLE
Batch Inference with XComposer2

### ISSUE THREAD

**Issue by boofarboofar** [InternLM/InternLM-XComposer#171]
Hello!

Are there any examples on asking multiple questions of the same image via batch?  Easy enough to do this serially, but slow.  I see there is ShareCaptioner, but looking for this for XComposer2.

**Comment by bingwork** [comment]
I am referring to https://github.com/InternLM/InternLM-XComposer/blob/main/evaluation/mmbench/utils.py#L110 to rewrite it. There are still some problems at present. It would be better if the official could provide a script. 
@myownskyW7

**Comment by panzhang0212** [comment]
We have supported Batch Inference with XComposer2, pleaser refer to https://github.com/InternLM/InternLM-XComposer/blob/main/examples/batch_chat.py

Free free to reopen this issue if you have any problems.
