### ISSUE TITLE
PLoRA disappears when applying lora.

### ISSUE THREAD

**Issue by yunsangju** [InternLM/InternLM-XComposer#173]
hello.
When I apply lora to the decoder, the existing model structure, PLoRA, is converted to linear.
I don't think this will utilize the existing PLoRA that you have learned.
Is this okay?

- Before applying lora
<img width="626" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/136311766/19e62fa0-5481-469a-8f53-04afa016c84c">

- After applying lora
<img width="763" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/136311766/e9ac66ef-ebdc-4fc8-a383-d2ed1a6ce04f">

**Comment by yuhangzang** [comment]
This issue has been fixed by the commit **3c522e7**. You can pull the latest version of fine-tune code to check if the problem still exists.

**Comment by myownskyW7** [comment]
@yunsangju

**Comment by yunsangju** [comment]
@yuhangzang @myownskyW7 
hello.
When I proceed with the code below, PLoRA still disappears.
```python
for name, param in model.model.named_parameters():
            param.requires_grad = False
        lora_config = LoraConfig(
            r=lora_args.lora_r,
            lora_alpha=lora_args.lora_alpha,
            target_modules=lora_args.lora_target_modules,
            lora_dropout=lora_args.lora_dropout,
            bias=lora_args.lora_bias,
            task_type='CAUSAL_LM',
        )

        model = get_peft_model(model, lora_config)
```
