### ISSUE TITLE
finetune时如何支持单卡组batch训练呢？

### ISSUE THREAD

**Issue by Marcovaldon** [InternLM/InternLM-XComposer#176]
如题，finetune时如何支持单卡内组batch训练呢？

我把finetune.sh中的--batch_size和--per_device_train_batch_size参数都改成了2，启动训练后会在下面位置报错
https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L266

报错原因是两个样本的token seq长度不一致，无法进行concatenate操作。

**Comment by yuhangzang** [comment]
You can ensure the equal number of <ImageHere> in the same JSON file. Or you can manually add an extra padding operator before concatenating.

**Comment by Marcovaldon** [comment]
I tried to add an extra padding operator before concatenating, then there is another error: 

`Traceback (most recent call last):
  File "finetune.py", line 312, in <module>
    train()
  File "finetune.py", line 302, in train
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2690, in training_step
    self.accelerator.backward(loss)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1960, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1890, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1953, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 871, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1332, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 906, in reduce_independent_p_g_buckets_and_remove_grads
    assert self.params_already_reduced[param_id] == False, \
AssertionError: The parameter 935 has already been reduced.             Gradient computed twice for this partition.             Multiple gradient reduction is currently not supported`

How to debug it?

**Comment by Marcovaldon** [comment]
@myownskyW7  @yuhangzang   I used only one sample to train with batch>1, there is the same error above.

**Comment by yuhangzang** [comment]
Can you provide more details on how you add the padding?

**Comment by Marcovaldon** [comment]
> Can you provide more details on how you add the padding?

After https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L266, I implement the padding procedure by below: 

`longest_token_num = max([wrap_embeds_list[j].shape[1] for j in range(len(img_list))])
        for i in range(len(img_list)):
            padding_num = longest_token_num - wrap_embeds_list[i].shape[1]
            if padding_num == 0: continue
            pad1 = torch.zeros((1, padding_num, 4096)).to(self.device)
            pad1 = pad1.type_as(wrap_embeds_list[i])
            wrap_embeds_list[i] = torch.cat([wrap_embeds_list[i], pad1], dim=1)

            pad2 = torch.zeros((1, padding_num)).to(self.device)
            pad2 = pad2.type_as(wrap_atts_list[i])
            wrap_atts_list[i] = torch.cat([wrap_atts_list[i], pad2], dim=1)

            pad3 = torch.ones((1, padding_num)).to(self.device) * self.tokenizer.pad_token_id
            pad3 = pad3.type_as(wrap_target_list[i])
            wrap_target_list[i] = torch.cat([wrap_target_list[i], pad3], dim=1)

            pad4 = torch.zeros((1, padding_num)).to(self.device)
            pad4 = pad4.type_as(wrap_im_mask_list[i])
            wrap_im_mask_list[i] = torch.cat([wrap_im_mask_list[i], pad4], dim=1)`

By the way, I used the original code and used only one sample (repeated 10w times) to train with batch > 1, there is the same error.

> AssertionError: The parameter 935 has already been reduced. Gradient computed twice for this partition. Multiple gradient reduction is currently not supported

**Comment by yuhangzang** [comment]
You may avoid in-place variable replacement and define other variables instead.

**Comment by will-wiki** [comment]
同样在batch训练的时候碰到了这个问题，看样子是推理过程中这个函数没有做padding导致序列不一致，想问下batch=1跟batch>1训练效果差别大么？  另外想问下你们内部训练就是用batch=1跑的吗？
<img width="830" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/22003927/426a6db7-b3e5-4365-a31a-fe0ed57ce6c1">
如果要添加padding，文本长度和图片个数都不一定能保持一致，图像padding跟文本padding是否要一致呢，不知道你们内部是如何处理的，能不能麻烦给点建议呢～

**Comment by Marcovaldon** [comment]
> I mean you may avoid the in-place replacement such as `wrap_embeds_list[i] = torch.cat([wrap_embeds_list[i], pad1], dim=1)`, and define new variables, e.g., `wrap_embeds_list_new[i] = torch.cat([wrap_embeds_list[i], pad1], dim=1)`

试过了还是相同的报错信息。想问一下作者在finetune的时候有组batch吗？    

我用最原始的代码做了一下尝试：训练数据为相同的10w case，此时在https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L266处组batch时是可以跑过去的（同一条case得到的序列长度肯定是相同的），但在后面做梯度反传的时候还是会有下面的问题：

> AssertionError: The parameter 935 has already been reduced. Gradient computed twice for this partition. Multiple gradient reduction is currently not supported

**Comment by decreasbetter** [comment]
> > I mean you may avoid the in-place replacement such as `wrap_embeds_list[i] = torch.cat([wrap_embeds_list[i], pad1], dim=1)`, and define new variables, e.g., `wrap_embeds_list_new[i] = torch.cat([wrap_embeds_list[i], pad1], dim=1)`
> 
> 试过了还是相同的报错信息。想问一下作者在finetune的时候有组batch吗？
> 
> 我用最原始的代码做了一下尝试：训练数据为相同的10w case，此时在[https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L266处组batch时是可以跑过去的（同一条case得到的序列长度肯定是相同的），但在后面做梯度反传的时候还是会有下面的问题：](https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L266%E5%A4%84%E7%BB%84batch%E6%97%B6%E6%98%AF%E5%8F%AF%E4%BB%A5%E8%B7%91%E8%BF%87%E5%8E%BB%E7%9A%84%EF%BC%88%E5%90%8C%E4%B8%80%E6%9D%A1case%E5%BE%97%E5%88%B0%E7%9A%84%E5%BA%8F%E5%88%97%E9%95%BF%E5%BA%A6%E8%82%AF%E5%AE%9A%E6%98%AF%E7%9B%B8%E5%90%8C%E7%9A%84%EF%BC%89%EF%BC%8C%E4%BD%86%E5%9C%A8%E5%90%8E%E9%9D%A2%E5%81%9A%E6%A2%AF%E5%BA%A6%E5%8F%8D%E4%BC%A0%E7%9A%84%E6%97%B6%E5%80%99%E8%BF%98%E6%98%AF%E4%BC%9A%E6%9C%89%E4%B8%8B%E9%9D%A2%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%9A)
> 
> > AssertionError: The parameter 935 has already been reduced. Gradient computed twice for this partition. Multiple gradient reduction is currently not supported

您好，请问padding的数值是如何设置的？有什么参考吗？

**Comment by yuhangzang** [comment]
We have already supported the batch size > 1 in the fine-tuning code for IXC 2.5. You can refer to [our implementation](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/main/modeling_internlm_xcomposer2.py#L290).

**Comment by Coobiw** [comment]
Hi, @yuhangzang . Thanks for this great work! In my opinion, the `batch_size` here works more similar to `sequence packing`. I think you should rename it to advoid some mistakes.
