### ISSUE TITLE
Question about model config.

### ISSUE THREAD

**Issue by liuxianyi** [InternLM/InternLM-XComposer#178]
```python
    gen_config = dict(
        num_beams=5,
        do_sample=False,
        min_length=1,
        repetition_penalty=1.5,
        length_penalty=1.0,
        temperature=1.0,
        max_new_tokens=500,
    )
```
what is the `num_beams` and `do_sample`? when composed, how will they take effect?

**Comment by yhcao6** [comment]
- `num_beams` is related to beam search and determines how many candidate sequences are considered at each step of the generation process. A higher value can lead to better quality outputs but requires more computational resources.
- `do_sample` decides whether the generation process should randomly sample from the probability distribution of next tokens, or just choose the highest probability next token at each step.

You can refer to https://huggingface.co/docs/transformers/generation_strategies for more details.
