### ISSUE TITLE
Are the pictures automatically selected after generating the article or do they need to be selected manually?

### ISSUE THREAD

**Issue by 2132660698** [InternLM/InternLM-XComposer#18]
请问生成文章后的图片是自动选择的还是需要手动选择？
![image](https://github.com/InternLM/InternLM-XComposer/assets/94035926/ca4d741f-e34e-4d91-aca8-96564d150568)

**Comment by myownskyW7** [comment]
图片会自动插入，写完文章会有个进度条，进度条走完就会展示插图。如果插图没有正常执行的话，可以把命令行的log贴出来，我们看一下。

The image will be inserted automatically, and a progress bar will appear once the article is written. When the progress bar completes, the images will be displayed. If the illustration does not execute properly, you can post the command line's log, and we can take a look.

**Comment by panzhang0212** [comment]
刚刚修复了这个bug，请clone最新的代码，得到以下输出
Just fix the bug of stopping criteria, please clone the newest code, and you can get the outputs below:
![image](https://github.com/InternLM/InternLM-XComposer/assets/30363822/f4d50553-abb3-411e-91d6-8cd15fdd72d1)

**Comment by 2132660698** [comment]
更新后就可以了，感谢你们的工作！
期待能放出后面的图库定制方法，这样可以做自己领域的写作定制。
