### ISSUE TITLE
LoRA微调后的InternLM-XComposer2-VL-7B 无法加载

### ISSUE THREAD

**Issue by seifer08ms** [InternLM/InternLM-XComposer#180]
根据 [微调文档Readme](https://github.com/InternLM/InternLM-XComposer/blob/main/finetune/README.md) [安装环境](https://github.com/InternLM/InternLM-XComposer/blob/main/docs/install_CN.md)准备数据，微调`internlm-xcomposer2-vl-7b`。训练后根据文档方法加载LoRA权重，出现问题：
`ValueError: Tokenizer class InternLMXComposer2Tokenizer does not exist or is not currently imported.`
![image](https://github.com/InternLM/InternLM-XComposer/assets/506463/049a767b-e9e0-4abb-a3b6-709733c4abb9)
尝试升级transformers到4.33.2，未解决。尝试升级transformers到最新版本，会提示 要设置`trust_remote_code=True`，但代码里已经设置为True：
```
The repository for /root/InternLM-XComposer/finetune/output/finetune/checkpoint-1375 contains custom code which must be execu
ted to correctly load the model. You can inspect the repository content at https://hf.co//root/InternLM-XComposer/finetune/ou
tput/finetune/checkpoint-1375.                                                                                               
You can avoid this prompt in future by passing the argument `trust_remote_code=True`. 
```

**Comment by yuhangzang** [comment]
The discussion in this issue may be helpful for you: https://github.com/THUDM/ChatGLM3/issues/826

**Comment by seifer08ms** [comment]
> The discussion in this issue may be helpful for you: [THUDM/ChatGLM3#826](https://github.com/THUDM/ChatGLM3/issues/826)

What is the actual meaning of updating hf model files in their discussion?

**Comment by yuhangzang** [comment]
You may check whether your local HF model matches the newest HF version [f8e6ab8](https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/tree/main)
