### ISSUE TITLE
batch finetune 模型时报错

### ISSUE THREAD

**Issue by will-wiki** [InternLM/InternLM-XComposer#182]
在batch训练的时候碰到了下面这个问题
```
 File "/home/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/modeling_internlm_xcomposer2.py", line 335, in forward
    to_regress_embeds, attention_mask, targets, im_mask = self.interleav_wrap(
  File "/home/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/modeling_internlm_xcomposer2.py", line 262, in interleav_wrap
    wrap_embeds = torch.cat(wrap_embeds_list)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 1284 but got size 1304 for tensor number 1 in the list.
```
看样子是推理过程中这个函数没有做padding导致序列不一致
<img width="830" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/22003927/426a6db7-b3e5-4365-a31a-fe0ed57ce6c1">

关于xcomposer2模型的finetune有几个问题想请教一下：
1.xcomposer2-vl-7b跟xcomposer-7b对于图片序列化的处理不一样，前者序列长度256，后者序列长度1225，按照llm最大默认长度4096来说xcomposer2-vl-7b基本是处理不了几张图片的，所以想问下如果想基于xcomposer2系列模型做视频级别的问答，用哪个模型好一些呢，xcomposer2系列模型内部有做视频级别的效果测试么？
2.batch=1跟batch>1训练效果差别大么？  内部训练是用batch=1跑的么，如果要添加padding，文本长度和图片个数都不一定能保持一致，图像padding跟文本padding是否要一致呢

最近一直在试用xcomposer模型，效果很棒，希望能给点建议，十分感谢！

**Comment by yuhangzang** [comment]
Thanks for your compliment on our project!

1. We suggest you use xcomposer2-vl-7b for video understanding. The xcomposer2-7b model is designed for text-image composition and is not well aligned on image/video understanding.

2. You may add additional padding operators to support batch>1. Since our SFT data is much smaller compared to the pre-train data, we do not observe differences in batch size.

**Comment by will-wiki** [comment]
@yuhangzang  
感谢回复～
不过使用xcomposer2-vl-7b模型，感觉图像序列的输入长度有点太大了，目前能想到两种sft的处理办法
1.增大模型的输入长度，比如设置成10240等。因为输入视频需要抽取多帧，提供8张以上的图片序列输入基本就快过万了，太短不适合做视频理解，但是太长的输入也会导致模型推理性能过慢从而不可用。
2.sft的时候将模型处理的图像分辨率调小，比如xcomposer2-7b那样变成16x16的长度，不过暂时不清楚这个更改会不会导致跟pretrain阶段gap太大影响效果

更倾向于处理办法2，想请教下这个可行性多大呢，或者博主有没有其他更好的建议呢～

**Comment by will-wiki** [comment]
@yuhangzang 
想问下，finetune脚本里，数据的获取为什么要用randomrange呢，那岂不是没法保证数据集能够完全轮训一遍，而且有些数据还可能会重复训练，其中Mix_dataset的get_item也是采用的random的形式，这个是有什么原因么
https://github.com/InternLM/InternLM-XComposer/blob/96731ae522019a90068f8e404d76d347f92a8bcb/finetune/data_mix.py#L156

如果有空，上面的问题也麻烦解答一下吧，另外想问下有没有什么交流群什么的呢，这里沟通有点不方便感觉

**Comment by yuhangzang** [comment]
> @yuhangzang 感谢回复 不过使用xcomposer2-vl-7b模型，感觉图像序列的输入长度有点太大了，目前能想到两种sft的处理办法 1.增大模型的输入长度，比如设置成10240等。因为输入视频需要抽取多帧，提供8张以上的图片序列输入基本就快过万了，太短不适合做视频理解，但是太长的输入也会导致模型推理性能过慢从而不可用。 2.sft的时候将模型处理的图像分辨率调小，比如xcomposer2-7b那样变成16x16的长度，不过暂时不清楚这个更改会不会导致跟pretrain阶段gap太大影响效果
> 
> 更倾向于处理办法2，想请教下这个可行性多大呢，或者博主有没有其他更好的建议呢～

I believe that adapting xcomposer2 for video understanding is still an open research question. The second solution seems reasonable to me and might be worth exploring further.

**Comment by yuhangzang** [comment]
> @yuhangzang 想问下，finetune脚本里，数据的获取为什么要用randrange呢，那岂不是没法保证数据集能够完全轮训一遍，而且有些数据还可能会重复训练，其中Mix_dataset的get_item也是采用的random的形式，这个是有什么原因么
> 
> https://github.com/InternLM/InternLM-XComposer/blob/96731ae522019a90068f8e404d76d347f92a8bcb/finetune/data_mix.py#L156
> 
> 如果有空，上面的问题也麻烦解答一下吧～ 另外想问下有没有什么交流群什么的呢，这里沟通有点不方便感觉

1. We encourage you to customize the dataloader to suit your specific needs. Given that our dataset consists of multiple JSON files, our approach starts by randomly choosing one JSON file from the list. After that, we select the data sample from within the chosen JSON file. This method allows for a more diverse data selection process. Feel free to adjust it as necessary for your project.

2. You can post your discussion on [Discord](https://discord.gg/xa29JuW87d) and [WeChat](https://r.vansin.top/?r=internwx).

**Comment by will-wiki** [comment]
@yuhangzang 有个问题想请教下～
finetune代码里 数据构造是不加任何的前置prompt
https://github.com/InternLM/InternLM-XComposer/blob/96731ae522019a90068f8e404d76d347f92a8bcb/finetune/data_mix.py#L11

但是不管是xcomposer2-vl还是xcomposer2模型在gradio服务上都是有固定的meta前置prompt，尝试过不加任何前置prompt效果会变得很差基本不可用，想问下这里finetune代码为什么没有加类似的前置prompt呢？
尝试进一步finetune，需要保持跟chat_meta一致的前置prompt么，直觉上觉得是不用 但是训练不加前置prompt是不是效果会差一些？
https://github.com/InternLM/InternLM-XComposer/blob/96731ae522019a90068f8e404d76d347f92a8bcb/examples/gradio_demo_chat.py#L29

**Comment by iFe1er** [comment]
同问，
1. chat_meta的前置prompt能否支持在finetune中加入？像Xtuner的微调是支持system prompt输入的。
2. 另外，XComposer2VL-Chat的finetune支持多轮对话吗？如果希望使用多轮对话数据，conversations中应该如何输入？比如下面两种方式：
```
{
      "id": "0",
      "image": ['path/to/image_0.jpg']
      "conversations": [
        {
          "from": "user",
          "value": "<ImageHere>问题1"
        },
        {
          "from": "assistant",
          "value": "回答1"
        },
        {
          "from": "user",
          "value": "问题2"
        },
        {
          "from": "assistant",
          "value": "回答2"
        }
      ]
    }, ...
```
还是：
{
      "id": "0",
      "image": ['path/to/image_0.jpg']
      "conversations": [
        {
          "from": "user",
          "value": "<ImageHere>问题1"
        },
        {
          "from": "assistant",
          "value": "回答1"
        },
       {
          "from": "user",
          "value": "<ImageHere>问题1 <eos>回答1<eos>问题2"
        },
        {
          "from": "assistant",
          "value": "回答2"
        },
      ]
    }, ...

呢？如果是第二种，<eos>应该怎么给？

p.s. 注意到你们团队的Xtuner库，对多轮对话的支持很不错（https://github.com/InternLM/xtuner/blob/main/docs/en/user_guides/dataset_format.md#multi-turn-dialogue-dataset-format），其实我的问题对到Xtuner，其实就是问XComposer2VL-Chat中实现多轮对话具体是对应Xtuner里面的method1还是method2。

当然未来能实现Xtuner method的方式是最好的。

**Comment by will-wiki** [comment]
@yuhangzang 
请教下大佬，最近一直在用灵笔2模型做实验，图像类效果很好，但是对于多图这种视频类效果相对一般，想请教下灵笔2模型有没有后续的迭代规划呢，是进一步优化图像模态的效果还是增加视频侧的能力呢

**Comment by alexhe101** [comment]
> 同问，
> 
> 1. chat_meta的前置prompt能否支持在finetune中加入？像Xtuner的微调是支持system prompt输入的。
> 2. 另外，XComposer2VL-Chat的finetune支持多轮对话吗？如果希望使用多轮对话数据，conversations中应该如何输入，历史消息需要在user的值中重复吗？比如下面两种方式：
> 
> ```
> {
>       "id": "0",
>       "image": ['path/to/image_0.jpg']
>       "conversations": [
>         {
>           "from": "user",
>           "value": "<ImageHere>问题1"
>         },
>         {
>           "from": "assistant",
>           "value": "回答1"
>         },
>         {
>           "from": "user",
>           "value": "问题2"
>         },
>         {
>           "from": "assistant",
>           "value": "回答2"
>         }
>       ]
>     }, ...
> ```
> 
> 还是：
> 
> ```
> {
>       "id": "0",
>       "image": ['path/to/image_0.jpg']
>       "conversations": [
>         {
>           "from": "user",
>           "value": "<ImageHere>问题1"
>         },
>         {
>           "from": "assistant",
>           "value": "回答1"
>         },
>        {
>           "from": "user",
>           "value": "<ImageHere>问题1<eos><sos>回答1<eos><sos>问题2<eos>"
>         },
>         {
>           "from": "assistant",
>           "value": "回答2"
>         },
>       ]
>     }, ...
> ```
> 
> 呢？
> 
> p.s. 注意到你们团队的Xtuner库，对多轮对话的支持很好。（[https://github.com/InternLM/xtuner/blob/main/docs/en/user_guides/dataset_format.md#multi-turn-dialogue-dataset-format）](https://github.com/InternLM/xtuner/blob/main/docs/en/user_guides/dataset_format.md#multi-turn-dialogue-dataset-format%EF%BC%89)
> 
> 3.其实我上面的问题对应到Xtuner，其实就是问XComposer2VL-Chat中实现多轮对话具体是对应Xtuner里面的**_损失计算方式_**，实际上属于method1还是method2呢？
> 
> 求解答，谢谢🙏
> 
> @yuhangzang

您好，请问这个finetune代码多轮对话吗？

**Comment by yuhangzang** [comment]
We provide the fine-tuning code of [IXC 2.5](https://github.com/InternLM/InternLM-XComposer/tree/main/finetune), which supports (1) batch size > 1 (2) multi-turn, multi-images conversation. Feel free to try our latest examples.
