### ISSUE TITLE
Clarification about the InternLM-XComposer2 LLM

### ISSUE THREAD

**Issue by MalvinaNikandrou** [InternLM/InternLM-XComposer#183]
Hi! 

Thank you for making your models public :)

In your paper, you mention that "In practical applications, we utilize the InternLM2-7B-Chat-SFT variant as our LLM.". 

Does that mean that _all_ models in the InternLM-XComposer2 series use the Chat-SFT variant as the LLM?

**Comment by yuhangzang** [comment]
*all* models use https://huggingface.co/internlm/internlm2-chat-7b as the LLM

**Comment by yuhangzang** [comment]
Please feel free to reopen this issue if you have any further questions.

**Comment by MalvinaNikandrou** [comment]
Thank you for the quick reply!
