### ISSUE TITLE
Add English commercial questionnaire

### ISSUE THREAD

**Issue by c2huc2hu** [InternLM/InternLM-XComposer#193]
In the README, there's no link for the application form in English (although the Chinese page points to https://wj.qq.com/s2/12725412/f7c1/). Is there a translation? My company won't sign off on anything not in English. Would it be possible to add an English version? Thanks! 

> The code is licensed under Apache-2.0, while model weights are fully open for academic research and also allow free commercial usage. To apply for a commercial license, please fill in the application form (English)/申请表（中文）. For other questions or collaborations, please contact [internlm@pjlab.org.cn](mailto:internlm@pjlab.org.cn).

**Comment by myownskyW7** [comment]
Hi, it has been updated here https://github.com/InternLM/InternLM-XComposer?tab=readme-ov-file#license--contact-us. This is the link to the English form https://wj.qq.com/s2/12727483/5dba/.

**Comment by myownskyW7** [comment]
Please do not hesitate to contact me if there are any questions.

**Comment by c2huc2hu** [comment]
Awesome, thank you very much
