### ISSUE TITLE
training data?

### ISSUE THREAD

**Issue by lucasjinreal** [InternLM/InternLM-XComposer#20]
Will release training data?

**Comment by myownskyW7** [comment]
Part of our private training data is released at https://github.com/opendatalab/WanJuan1.0.

**Comment by lucasjinreal** [comment]
@myownskyW7 what about else, how many data overall used in training? and what's the postion of English and Chinese data?

**Comment by myownskyW7** [comment]
Here are details about our pretraining and fine-tuning data.
**1. Pretraining Data**:
![image](https://github.com/InternLM/InternLM-XComposer/assets/9253073/e41b94be-c637-4444-b32f-2392b47d8183)
**2. Finetuning Data**:
![image](https://github.com/InternLM/InternLM-XComposer/assets/9253073/cf4566cb-2ca8-483e-bd83-df6e9cab8304)
Please refer to our [technical report](https://arxiv.org/pdf/2309.15112.pdf) for other details.
