### ISSUE TITLE
couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14-336 is not the path to a directory containing a file named config.json.

### ISSUE THREAD

**Issue by Litong-sTs** [InternLM/InternLM-XComposer#206]
couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14-336 is not the path to a directory containing a file named config.json.请问一下，我是要下载这个openai/clip-vit-large-patch14-336模型配套使用吗？要是下载的话我要放在哪里，改哪里的代码？
![微信图片_20240306160447](https://github.com/InternLM/InternLM-XComposer/assets/106523197/782ef54e-2b9a-49c2-9574-52f47da4b4c6)

**Comment by yhcao6** [comment]
It seems your network fails to connect to huggingface.

You can manually download `openai/clip-vit-large-patch14-336`, then change the path in the function `build_vision_tower` to your local path as follows:

```
def build_vision_tower():
    # vision_tower = 'openai/clip-vit-large-patch14-336'
    vision_tower = your_local_path
    return CLIPVisionTower(vision_tower)
```

You can find the file define the function `build_vision_tower` in the error traceback.

**Comment by deku0818** [comment]
我更改了对应文件的函数，但是执行后就会恢复成原来的样子
