### ISSUE TITLE
请问两张32g v100运行 finetune.sh 报错OOM怎么办？

### ISSUE THREAD

**Issue by Qinger27** [InternLM/InternLM-XComposer#211]
你好！谢谢你们开源了这么棒的项目！
我在2张32g的v100卡上使用finetune.sh脚本基于自己的数据集训练时报错，而且貌似第二张卡没有用起来：
<img width="1189" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/73786265/23898a3d-7fae-4bfc-8aad-dbd0790f82de">
训练配置如下：
<img width="469" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/73786265/c3656fce-d9f6-4624-848c-47fea3a519a2">
可以帮忙看一下吗？非常感谢🙏

**Comment by thonglv21** [comment]
--max_length 2048 or 1024 or 512

**Comment by yuzeng0-0** [comment]
lora

**Comment by yuhangzang** [comment]
You can reduce the value of `max_length` of using a small value of `lora_r`/`lora_alpha` with lora fine-tuning.
