### ISSUE TITLE
How to use Wanjuan dataset

### ISSUE THREAD

**Issue by alexwangmac** [InternLM/InternLM-XComposer#216]
Hi, thank you for your amazing work. I would like to ask about the usage of "Wanjuan." I noticed in the article that you used the Wanjuan dataset during the pretraining phase. This dataset contains a mix of text and images, which is different from the format of VQA data. I'm curious to know how it was incorporated into the training process. Do you need to construct question prompts similar to VQA, such as "Given the context and the image, continue the passage"?  Additionally, the content in Wanjuan dataset seems quite diverse and only partially related to the images. Does training with this dataset pose a significant challenge or potential conflicts with other data, resulting in suboptimal performance?

**Comment by yuhangzang** [comment]
In the pre-training stage, we do not use any VQA prompts and do not face the problems you mentioned.
