### ISSUE TITLE
About SAM data

### ISSUE THREAD

**Issue by jiangsongtao** [InternLM/InternLM-XComposer#217]
你好,请问为什么我在openxlab网站上面下载的SA-1B，前51个tar,文件没有完全覆盖share-captioner_coco_lcs_sam_1246k_1107.json,每个文件解压出来的tar只有11186个jpg,51*11186没有1246k那么多

**Comment by jiangsongtao** [comment]
后面发现可能是下载的tar有损坏~

**Comment by codefanw** [comment]
你好，请问你有解决这个问题吗，我从openxlab下载0-50的tar压缩包，在解压时发现14 16 17 19是损坏的，但是其他正常的压缩包解压后仍然缺少share-captioner_coco_lcs_sam_1246k_1107.json中的570486张图片，仅含有676415张图片

**Comment by jiangsongtao** [comment]
我后面暂时把这些filter掉了，感觉这个数据集下载经常有问题，要是有直接压缩好的就好了~~
