### ISSUE TITLE
support for multi-turn dialogues training

### ISSUE THREAD

**Issue by alexhe101** [InternLM/InternLM-XComposer#218]
I am interested in understanding whether the current SFT code can support multi-turn dialogues training ？

**Comment by yuhangzang** [comment]
Yes, the format is like "conversations": [
{ "from": "user", "value": "<ImageHere> what is the color of the dog" }, { "from": "assistant", "value": "it is ...." },
...,
{ "from": "user", "value": "<ImageHere> what is the color of the dog" }, { "from": "assistant", "value": "it is ...." },
]

**Comment by alexhe101** [comment]
thank you for your reply
