### ISSUE TITLE
Url error in Chinese doc

### ISSUE THREAD

**Issue by cocoshe** [InternLM/InternLM-XComposer#223]
![image](https://github.com/InternLM/InternLM-XComposer/assets/69197635/8053b0aa-bf51-4341-b8e7-cfa3a0f743af)

https://github.com/InternLM/InternLM-XComposer/blob/417a911bed49ed02b96cdc83c8326d5596cce786/README_CN.md?plain=1#L52-L58

The hf url and modelscope url seem to be error.

**Comment by myownskyW7** [comment]
The URLs are now fixed. Thank you!
