### ISSUE TITLE
Regarding "<ImageHere>" 

### ISSUE THREAD

**Issue by thiner** [InternLM/InternLM-XComposer#225]
1. Is "<ImageHere>" a fixed placeholder in text prompt? 
2. What kind of value does the VL model expect? A path, URL or base64 encoded image?

**Comment by yuhangzang** [comment]
Hi thiner, you may refer to this [line](https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L134) and this [line](https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L109) for your questions.

**Comment by thiner** [comment]
@yhcao6 Thanks for your answer. 
I'd like to summarize my study from the code, please correct me if I am wrong.

1. `<ImageHere>` is a fixed placeholder which separate image and text prompt. 
2. XComposer-VL expects the image input be a path which is recognizable by `PIL.Image.open` method or a `torch.Tensor` instance.

Based on above summaries,  I have a further question, does XComposer-VL supports multiple images as input? I think it's not supported currently, is it?

**Comment by yuhangzang** [comment]
XComposer-VL supports multiple images as input, e.g., query = '<ImageHere> <ImageHere> balabala', img_path = ['a.jpg', 'b.jpg']

**Comment by yuhangzang** [comment]
Kindly reopen this issue if you have any further questions.

**Comment by yuhangzang** [comment]
Kindly reopen this issue if you have any further questions.
