### ISSUE TITLE
fintune.sh的时候出错 A change in max_length causes loss to remain 0

### ISSUE THREAD

**Issue by decreasbetter** [InternLM/InternLM-XComposer#227]
当我max_length由4096变为2048进行微调时，loss一直为0。但是将max_length改为4096时loss正常

**Comment by yuhangzang** [comment]
Can you set a breakpoint (e.g., ``pdb. set_trace()`` ) [here](https://huggingface.co/internlm/internlm-xcomposer2-vl-7b/blob/main/modeling_internlm_xcomposer2.py#L214) and check the value of the `text' variable?

**Comment by decreasbetter** [comment]
已经解决问题了，谢谢！
问题补充：
当我更新vit的参数时，训练完成后，加载权重时会出现tesor张量不匹配，是因为在加载模型的时候需要加载新的Clip-Vision模型权重吗？但是我在训练好的模型文件中并没找到对应的权重

**Comment by yuhangzang** [comment]
Our checkpoint has the following structure and the CLIP-ViT can be found in the `.vit` submodule.

InternLM2ForCausalLM(
  (model): InternLM2Model(...),
  (output): Linear(...),
  (vit): CLIPVisionTower(...),
  (vision_proj): Sequential(...),
)

**Comment by decreasbetter** [comment]
我如何加载这样的模型呢，有示例的代码吗

**Comment by thonglv21** [comment]
> The problem has been solved, thank you! 

How did you solve the problem?

**Comment by chuangzhidan** [comment]
> 已经解决问题了，谢谢！ 问题补充： 当我更新vit的参数时，训练完成后，加载权重时会出现tesor张量不匹配，是因为在加载模型的时候需要加载新的Clip-Vision模型权重吗？但是我在训练好的模型文件中并没找到对应的权重

请问你是怎么解决的？

**Comment by decreasbetter** [comment]
> > The problem has been solved, thank you!
> 
> How did you solve the problem?

我查看了一张图片的输入tokens差不多是1200，当我输入的图片超过三张时，光图片的token就已经大幅度超过max_length了，超出部分会被截断。而指令一般是加载在图片之后的，所以这个时候会导致微调的指令缺失以及部分图片的缺失。我增大了max_length为4096后就不会出现这个问题，我想图片输入数量变少也可以解决问题

**Comment by decreasbetter** [comment]
> > 已经解决问题了，谢谢！ 问题补充： 当我更新vit的参数时，训练完成后，加载权重时会出现tesor张量不匹配，是因为在加载模型的时候需要加载新的Clip-Vision模型权重吗？但是我在训练好的模型文件中并没找到对应的权重
> 
> 请问你是怎么解决的？

参考刚刚的回复

**Comment by chuangzhidan** [comment]
所以单张图片更新vit参数时不需要变更，直接train？
