### ISSUE TITLE
请教一下，最大长度的问题

### ISSUE THREAD

**Issue by mzfive** [InternLM/InternLM-XComposer#231]
看参数最大长度是4096，想问一下这个长度在a100能训练起来么。这边测试会oom

**Comment by yuhangzang** [comment]
You may try the LoRA fine-tuning with a small value of $r$ to avoid the oom issue.

**Comment by yuhangzang** [comment]
I hope this clarifies! If you have any more questions, feel free to re-open this issue. 😊
