### ISSUE TITLE
可以公开 灵笔2 的 图文预训练后的参数 吗？

### ISSUE THREAD

**Issue by zzf-damon** [InternLM/InternLM-XComposer#242]
我们想要探究一下对其预训练的工作对于多模态训练的必要性。
咱们可以公开 灵笔2 的 图文预训练的参数吗？
在论文 《InternLM-XComposer2: Mastering Free-form Text-Image Composition and Comprehension in Vision-Language Large Models》3.2. Pre-Training  中提到的模型

**Comment by luohao123** [comment]
InternVit6B?
