### ISSUE TITLE
在geo3k数据集上利用finetune_lora.sh进行微调，微调后的权重和初始化的相同，和以下警告有关系请给我提供一些帮助，谢谢

### ISSUE THREAD

**Issue by dle666** [InternLM/InternLM-XComposer#246]
![1712313679864](https://github.com/InternLM/InternLM-XComposer/assets/107533509/623c9d23-13fd-45e4-93c3-477fd2cc3f3e)

**Comment by dle666** [comment]
@myownskyW7 @yeyimilk @LightDXY @eltociear

**Comment by yeyimilk** [comment]
Which version of transformer did you use？

I got some other errors, but fixed when change the transformers to 
> transformers==4.33.2
