### ISSUE TITLE
Context length during training?

### ISSUE THREAD

**Issue by ys-zong** [InternLM/InternLM-XComposer#247]
Hi, thanks for the nice work! I saw the `max_position_embeddings` is set to 32768 in the [`config.json`](https://huggingface.co/internlm/internlm-xcomposer2-7b/blob/main/config.json). This is quite large. I wonder what is the context length you use during training? I didn't find it in the report. Many thanks!

**Comment by LightDXY** [comment]
hi, for the xcomposer2, most data has less than 4096 tokens. 32768 is the max length supported by the LLM backbone InternLM2. For our new xcomposer2-4khd, it is trained with nearly 8k tokens per sample.
