### ISSUE TITLE
How to do VQA task by image url with <internlm-xcomposer2-4khd-7b>? 

### ISSUE THREAD

**Issue by XKCUW** [InternLM/InternLM-XComposer#255]
I can use "vis_processor" method to get the embedding of the image manually(through url)  on <internlm-xcomposer2-vl-7b>, like the method used  in <internlm-xcomposer2-7b>.
(refer: https://huggingface.co/internlm/internlm-xcomposer2-7b).
However, I tried the same way on <internlm-xcomposer2-4khd-7b>, it doesn't work.
could you give some examples to solve the issue?
@panzhang0212  @yhcao6

**Comment by LightDXY** [comment]
https://github.com/open-compass/VLMEvalKit/blob/main/vlmeval/vlm/xcomposer/xcomposer2_4KHD.py#L60
you could define the text and image, and the image resolution freely with this function, this repo also supports many mainstream VQA benchmarks.
