### ISSUE TITLE
Grounding ability of xcomposer2-4khd 

### ISSUE THREAD

**Issue by laserwave** [InternLM/InternLM-XComposer#261]
xcomposer2-4khd是否支持REC（reference expression comprehension）和REG（reference expression generation）任务呢，动态分辨率是否难以学习这两个任务

**Comment by LightDXY** [comment]
hi, this is an interesting question, our 4khd model indeed supports grounding (btw, the xcompoer2 also has strong grounding capability), we provide the image width and height to the model, and predict the pixel directly, here are a few examples. 4khd works well on Images with different sizes.

1. ![image](https://github.com/InternLM/InternLM-XComposer/assets/18134953/71b2f726-a01d-4695-b068-5e606dc29a54)
2. ![image](https://github.com/InternLM/InternLM-XComposer/assets/18134953/66b2da6e-6999-499f-8290-00bd81cb8724)
3. ![image](https://github.com/InternLM/InternLM-XComposer/assets/18134953/61a35827-9e12-4fd6-a4e2-079acfa76f4d)
4. ![image](https://github.com/InternLM/InternLM-XComposer/assets/18134953/867048c3-c560-4211-a718-bf2fc4116667)
5. ![image](https://github.com/InternLM/InternLM-XComposer/assets/18134953/09163b9c-0bbc-4895-a924-fb3d24297d07)

**Comment by laserwave** [comment]
thank you

**Comment by laserwave** [comment]
@LightDXY hi，does it support REG，i.e. image caption
 or vqa task corresponding to a given image region/bounding box

**Comment by LightDXY** [comment]
hi , REG is also supported, as it is a symmetrical task of grounding. 
For the vqa task corresponding to a given image region/bounding box, we do not use such data in the training.
