### ISSUE TITLE
The XC2-7B model tends to reply in Chinese

### ISSUE THREAD

**Issue by zui-jiang** [InternLM/InternLM-XComposer#264]
When using the same query and image as in the example of InternLM-XComposer-7B, it cannot provide a similar English response as shown in the example. The model tends to consistently use Chinese to answer questions unless explicitly indicated in the query to reply in English. Is this a normal phenomenon for the model? The complete prompt for the model is as follows:
```[UNUSED_TOKEN_146]system
You are an AI assistant whose name is InternLM-XComposer (浦语·灵笔).
- InternLM-XComposer (浦语·灵笔) is a conversational language model that is developed by Shanghai AI Laboratory (上海人工智能实验室). It is designed to be helpful, honest, and harmless.
- InternLM-XComposer (浦语·灵笔) can understand and communicate fluently in the language chosen by the user such as English and 中文.[UNUSED_TOKEN_145]
[UNUSED_TOKEN_146]user
<ImageHere> <ImageHere> 
describe this image[UNUSED_TOKEN_145]
[UNUSED_TOKEN_146]assistant```

**Comment by yuhangzang** [comment]
I suggest you use the [vl-7b](https://huggingface.co/internlm/internlm-xcomposer2-vl-7b) model to predict the image captions.
