### ISSUE TITLE
Interleaved inputs for InternLM-XC-4KHD

### ISSUE THREAD

**Issue by ys-zong** [InternLM/InternLM-XComposer#266]
Hi, thanks for the nice work! I wonder if InternLM-4KHD supports interleaved image-text (e.g. multiple images) inputs for inference like InternLM-XComposer?

**Comment by LightDXY** [comment]
hi, the model has such capability but is not good at it, as we do not train the model with interleaved data

**Comment by myownskyW7** [comment]
@ys-zong Hi, you may try to concatenate multiple images into a sinlge large image and ask the question.
