### ISSUE TITLE
Suggestion : make  examples/web_demo.py more secure

### ISSUE THREAD

**Issue by walkskysu** [InternLM/InternLM-XComposer#27]
change the last line in examples/web_demo.py to make more securte , Not everyone need expose service to public 

if __name__ == "__main__":
    demo.launch(share=True, server_name="0.0.0.0", server_port=11111)

to
   demo.launch(share=False, server_name="127.0.0.1", server_port=11111)

**Comment by myownskyW7** [comment]
Thank you for this constructive suggestion. We will update the code very soon.

**Comment by panzhang0212** [comment]
Thank you for the suggestion. The code currently supports private deployment by adding the `--private` option.
