### ISSUE TITLE
无法连接huggingface找到openai/clip-vit-large-patch14-336，请问这个模型离线怎么跑推理demo？

### ISSUE THREAD

**Issue by changqinyao** [InternLM/InternLM-XComposer#271]
openai/clip-vit-large-patch14-336路径封装在库里面，离线环境无法跑推理。

**Comment by LightDXY** [comment]
you could download the vit to your local path and set the path in the build_mlp.py to the local path

**Comment by deku0818** [comment]
> you could download the vit to your local path and set the path in the build_mlp.py to the local path

我修改了文件 vim /root/.cache/huggingface/modules/transformers_modules/build_mlp.py 并且将vision_tower = 'openai/clip-vit-large-patch14-336' 替换为了本地路径，但是再次执行就被重写覆盖了

**Comment by xiaoze1332** [comment]
> > you could download the vit to your local path and set the path in the build_mlp.py to the local path
> 
> 我修改了文件 vim /root/.cache/huggingface/modules/transformers_modules/build_mlp.py 并且将vision_tower = 'openai/clip-vit-large-patch14-336' 替换为了本地路径，但是再次执行就被重写覆盖了

你要修改下载的模型文件中的"build_mlp.py"，而不是修改.cache文件夹中的"build_mlp.py"

**Comment by zjtco-yr** [comment]
> > > you could download the vit to your local path and set the path in the build_mlp.py to the local path
> > 
> > 
> > 我修改了文件 vim /root/.cache/huggingface/modules/transformers_modules/build_mlp.py 并且将vision_tower = 'openai/clip-vit-large-patch14-336' 替换为了本地路径，但是再次执行就被重写覆盖了
> 
> 你要修改下载的模型文件中的"build_mlp.py"，而不是修改.cache文件夹中的"build_mlp.py"

thx，it works， hope you a happy day
