### ISSUE TITLE
When will the proj and vit freeze?

### ISSUE THREAD

**Issue by OpenJarvisAI** [InternLM/InternLM-XComposer#273]
if training_args.fix_vit:
        model.vit.requires_grad_(False)
    else:
        model.vit.requires_grad_(True)
        model.vit.vision_tower.vision_model.post_layernorm = torch.nn.Identity(
        )

    if training_args.fix_sampler:
        model.vision_proj.requires_grad_(False)
    else:
        model.vision_proj.requires_grad_(True)

but the finetune script always False??

**Comment by LightDXY** [comment]
If you finetune the model on a new task with large-scale images unseen before, maybe you could set them to learnable

**Comment by OpenJarvisAI** [comment]
I just ask what internvx does, I want re implement it from scratch.
