### ISSUE TITLE
为什么用4K模型训练时loss是0？

### ISSUE THREAD

**Issue by zweiqi** [InternLM/InternLM-XComposer#285]

**Comment by yuhangzang** [comment]
This is due to the incorrect SFT data format. You can set a breakpoint to view the value of the `text` variable in [here](https://huggingface.co/internlm/internlm-xcomposer2-4khd-7b/blob/main/modeling_internlm_xcomposer2.py#L218) to verify.

**Comment by yuhangzang** [comment]
Kindly re-open if you still have any issues.
