### ISSUE TITLE
微调internlm-xcomposer2-4khd-7b出错

### ISSUE THREAD

**Issue by 2132660698** [InternLM/InternLM-XComposer#288]
用最新的代码微调internlm-xcomposer2-4khd-7b，发生如下错误：
![image](https://github.com/InternLM/InternLM-XComposer/assets/94035926/b58b2571-70ac-4949-a61f-a14eff480cf4)
请问是不是Mix_dataset里面还没有加上hd_num参数，Sample_dataset已经加上了。

**Comment by 2132660698** [comment]
在Mix_dataset加上hd_num参数后跑起来报下面的错误：
![image](https://github.com/InternLM/InternLM-XComposer/assets/94035926/c6a3c8d7-bf2e-47c2-a6f2-f9fc3c867121)
![image](https://github.com/InternLM/InternLM-XComposer/assets/94035926/4a0e58b9-2ad9-48d5-b3c2-8cb39b180186)

**Comment by yuhangzang** [comment]
Thanks for your feedback! Can u retry the latest version?

**Comment by myownskyW7** [comment]
@2132660698 Please check this PR https://github.com/InternLM/InternLM-XComposer/pull/290
