### ISSUE TITLE
Thanks for your feedback! Can u retry the latest version?

### ISSUE THREAD

**Issue by 2132660698** [InternLM/InternLM-XComposer#291]
Thanks for your feedback! Can u retry the latest version?

_Originally posted by @yuhangzang in https://github.com/InternLM/InternLM-XComposer/issues/288#issuecomment-2071359528_
            你好，4.23日13点更新了代码，微调internlm-xcomposer2-4khd-7b报下面的错误，麻烦再看一下：
![image](https://user-images.githubusercontent.com/94035926/324700071-68aa2482-f540-41e8-b07b-18a148e43596.png)

**Comment by 2132660698** [comment]
![image](https://github.com/InternLM/InternLM-XComposer/assets/94035926/31b0be32-83d6-4f71-bba6-caab9c86fe3d)

**Comment by yuhangzang** [comment]
Hi, can u post the parameters of your `finetune_lora.sh` file?

**Comment by 2132660698** [comment]
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

# export MODEL="internlm/internlm-xcomposer2-7b"
# export MODEL="internlm/internlm-xcomposer2-vl-7b"
# export MODEL="internlm/internlm-xcomposer2-4khd-7b"
export MODEL="/data/internlm/internlm-xcomposer2-4khd-7b/"
# export DATA="data.txt"
export DATA="/data/internlm/InternLM-XComposer/finetune/data.txt"

GPUS_PER_NODE=1
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --img_size 490 \
    --hd_num 16 \
    --given_num True \
    --bf16 True \
    --fix_vit True \
    --fix_sampler True \
    --use_lora True \
    --output_dir output/finetune \
    --num_train_epochs 1 \
    --batch_size 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate 5e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --max_length 4096 \
    --deepspeed ds_config_zero2.json \
    --gradient_checkpointing True

**Comment by 2132660698** [comment]
![image](https://github.com/InternLM/InternLM-XComposer/assets/94035926/710f8b27-795b-4423-9ded-604665d51c7d)

**Comment by 2132660698** [comment]
这是我的微调数据：
![image](https://github.com/InternLM/InternLM-XComposer/assets/94035926/21897ce6-d7c8-48c6-b655-ba72b1883839)

**Comment by yuhangzang** [comment]
This issue is due to the current 4khd fine-tuning code does not support multiple images in one query. Please stay tuned.

**Comment by 2132660698** [comment]
> This issue is due to the current 4khd fine-tuning code does not support multiple images in one query. Please stay tuned.

应该是你说的这个情况，将训练数据中的多图改成一张图后，可以Lora训练完成。

**Comment by 2132660698** [comment]
请问Lora训练后，可以合并吗？

**Comment by yuhangzang** [comment]
Our [IXC 2.5](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/tree/main) has supported the multi-round, multi-image fine-tuning. We also provide the LoRA merge scripts [here](https://github.com/InternLM/InternLM-XComposer/blob/main/finetune/merge_peft_adapter.py)
