### ISSUE TITLE
求发布一个InternLM-XComposer2-4KHD的gradio_demo_composition.py

### ISSUE THREAD

**Issue by a136214808** [InternLM/InternLM-XComposer#294]
求发布一个InternLM-XComposer2-4KHD的gradio_demo_composition.py

**Comment by panzhang0212** [comment]
The 4KHD model is designed for multimodal understanding.  So it does not support for composition. 

We release the gradio code to chat with InternLM-XComposer2-4KHD. Please refer to

https://github.com/InternLM/InternLM-XComposer/blob/main/examples/gradio_4khd_chat.py

**Comment by yuhangzang** [comment]
Kindly re-open if you still have any issue.
