### ISSUE TITLE
我的机器无法连接到huggingface，但是下载了离线clip-vit无法使用

### ISSUE THREAD

**Issue by deku0818** [InternLM/InternLM-XComposer#295]
我修改了文件 vim /root/.cache/huggingface/modules/transformers_modules/build_mlp.py 并且将vision_tower = 'openai/clip-vit-large-patch14-336' 替换为了本地路径，但是再次执行就被重写覆盖了

**Comment by yuhangzang** [comment]
You may replace the `model = AutoModel.from_pretrained('internlm/internlm-xcomposer2-4khd-7b')` with `model = AutoModel.from_pretrained('xxx')`, where `xxx` is your local model path.

**Comment by deku0818** [comment]
> You may (1) download the HF repo into your local path, (2) modify the build_mlp.py and (3)replace the `model = AutoModel.from_pretrained('internlm/internlm-xcomposer2-4khd-7b')` with `model = AutoModel.from_pretrained('xxx')`, where `xxx` is your local model path.您可以（1）将 HF 仓库下载到本地路径，（2）修改 build_mlp.py，并（3）将 `model = AutoModel.from_pretrained('internlm/internlm-xcomposer2-4khd-7b')` 替换为 `model = AutoModel.from_pretrained('xxx')` ，其中 `xxx` 是您的本地模型路径。

![image](https://github.com/InternLM/InternLM-XComposer/assets/84755119/fc9b8dce-6838-40e9-bb9d-808b5925cf3f)
我指的是openai/clip-vit-large-patch14-336，我在运行internlm-xcomposer2-vl-7b报错了
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14-336 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
![image](https://github.com/InternLM/InternLM-XComposer/assets/84755119/1ce54ee9-ab6d-4686-b9ac-966e71628c18)

**Comment by yuhangzang** [comment]
Please down the xcomposer2-vl-7b HF repo into your local path, otherwise, your modification will be overwritten.

**Comment by deku0818** [comment]
> Please download the xcomposer2-vl-7b HF repo into your local path, otherwise, your modification will be overwritten.请将 xcomposer2-vl-7b HF 仓库下载到您的本地路径，否则，您的修改将被覆盖。

是的，做上述操作之前我已经下载到了本地路径..
![image](https://github.com/InternLM/InternLM-XComposer/assets/84755119/d089fd58-d70f-4fa9-9c27-9fbd5609e2f6)

**Comment by deku0818** [comment]
> Please download the xcomposer2-vl-7b HF repo into your local path, otherwise, your modification will be overwritten.请将 xcomposer2-vl-7b HF 仓库下载到您的本地路径，否则，您的修改将被覆盖。

依旧会被覆盖，我也尝试了用LMDeploy 部署，依旧失败
![image](https://github.com/InternLM/InternLM-XComposer/assets/84755119/27e9fdee-9100-4f30-810c-2783dee85841)

**Comment by tianyour** [comment]
> > 请将 xcomposer2-vl-7b HF 仓库下载到您的本地路径，否则，您的修改将被覆盖。
> 
> 依旧会被覆盖，我也尝试了用LMDeploy 部署，依旧失败 ![图像](https://private-user-images.githubusercontent.com/84755119/325852840-27e9fdee-9100-4f30-810c-2783dee85841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDA0MzYsIm5iZiI6MTcxNTc0MDEzNiwicGF0aCI6Ii84NDc1NTExOS8zMjU4NTI4NDAtMjdlOWZkZWUtOTEwMC00ZjMwLTgxMGMtMjc4M2RlZTg1ODQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAyMjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYjAzNDRlMGNjODVlOWY3ODUxYTNmYWRkYzNjNzNlNDJhMzhiZDY4NmFhYmQ0ZjZhZmI2YTE4OTQ0YWQ3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yIABPa8DlDtOkJ_7w_rK9tfFVXDMrKtx9sTpejZZrko)

请问这个问题解决了吗

**Comment by isruihu** [comment]
一样的问题，.cache/huggingface/modules/transformers_modules/build_mlp.py文件每次运行时候会刷新，导致无法从local加载openai/clip-vit-large-patch14-336
有人解决了吗

**Comment by tianyour** [comment]
您好，您的邮件我已收到，我将尽快查看！This is an automatic reply, confirming that your e-mail was received. Thank you

**Comment by tianyour** [comment]
您好，您的邮件我已收到，我将尽快查看！This is an automatic reply, confirming that your e-mail was received. Thank you

**Comment by ygzhu** [comment]
Just remove the `huggingface` dir in `.cache`, rectify the script in local path and run the code from scratch.

> 一样的问题，.cache/huggingface/modules/transformers_modules/build_mlp.py文件每次运行时候会刷新，导致无法从local加载openai/clip-vit-large-patch14-336 有人解决了吗

**Comment by tianyour** [comment]
您好，您的邮件我已收到，我将尽快查看！This is an automatic reply, confirming that your e-mail was received. Thank you

**Comment by zjtco-yr** [comment]
我遇到的一模一样的问题。。

**Comment by zjtco-yr** [comment]
我感觉这个issue需要重新打开

**Comment by tianyour** [comment]
您好，您的邮件我已收到，我将尽快查看！This is an automatic reply, confirming that your e-mail was received. Thank you
