### ISSUE TITLE
vit.vision_tower.vision_model.post_layernorm.weight & bias NOT initialized?

### ISSUE THREAD

**Issue by JasonLeeFdu** [InternLM/InternLM-XComposer#296]
![image](https://github.com/InternLM/InternLM-XComposer/assets/44363746/26be0121-2baf-464c-b744-a4bde6e407fe)

**Comment by JasonLeeFdu** [comment]
It says that there are 2 params which are not found in the pretrained weights. It is very unsettling since I copyed the code from huggingface-1.8B model card- quick start.
![image](https://github.com/InternLM/InternLM-XComposer/assets/44363746/0febb739-1a12-449e-b397-630d08e1c228)

**Comment by JasonLeeFdu** [comment]
Still
![image](https://github.com/InternLM/InternLM-XComposer/assets/44363746/73a9dfdc-df5d-489b-af4b-fa02d6e9347f)

**Comment by yuhangzang** [comment]
The `post_layernorm` is applied after the output of the ViT last layer, which is not used in our model and we delete them during training. So you can ignore this log, it does not affect the performance.
