### ISSUE TITLE
Curious about zero-shot performance for the pretrained VLLM

### ISSUE THREAD

**Issue by wjfwzzc** [InternLM/InternLM-XComposer#3]
1. Is the LLM part of [internlm-xcomposer-vl-7b](https://huggingface.co/internlm/internlm-xcomposer-vl-7b) the base version ([internlm-7b](https://huggingface.co/internlm/internlm-7b)) or the chat version ([internlm-chat-7b](https://huggingface.co/internlm/internlm-chat-7b) or [internlm-chat-7b-v1.1](https://huggingface.co/internlm/internlm-chat-7b-v1_1))?
2. If the LLM part is the base version, and there is no sft on xcomposer-vl, then how does it have the ability to follow the instructions of benchmarks to get high performance on zero-shot (instead of few-shot) testing?

**Comment by LightDXY** [comment]
Hi, thanks for your interest in our work, our model is based on the InternLM-Chat-7b-v1.0, so it still has the instruction-following capability after the multi-modal pretraining and SFT. We will clarify it in the README and the paper in the following update.
