### ISSUE TITLE
InternLM-XComposer-VL-7B, The chinese ability of the model does not match the demo.

### ISSUE THREAD

**Issue by felixfuu** [InternLM/InternLM-XComposer#30]
`
import torch
from transformers import AutoModel, AutoTokenizer

torch.set_grad_enabled(False)
model_path = "internlm/internlm-xcomposer-vl-7b"
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda().eval()
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model.tokenizer = tokenizer

image = "./image/aiyinsitan.jpg"
text = '请问这张图片里面的人是谁？并介绍下他。'
response = model.generate(text, image)
print(response)
`

`
response:  albert einstein
`

I tried a lot of pictures, but the effect of the model is not satisfactory, and the results are basically in English.

**Comment by WeiXuanLi-1024** [comment]
这个我也遇到过，使用 internlm-xcomposer 权重就好了，我猜测internlm-xcomposer-vl只在图文对上训练，可能对中文理解不好

**Comment by myownskyW7** [comment]
请使用 internlm-xcomposer 权重进行聊天，internlm-xcomposer-vl是预训练的模型。
