### ISSUE TITLE
Get the embeddings of the image.

### ISSUE THREAD

**Issue by xinyanghuang7** [InternLM/InternLM-XComposer#307]
Thank you very much for contributing such an excellent model!

If I want to input a picture and obtain the **embedding** provided by InternLM-XComposer2-VL-7B, how should I do it?

Can you help me implement it with a few simple lines of code?

Looking forward to your reply!

Thanks!

**Comment by yuhangzang** [comment]
If you want to get the input image embedding extracted by ViT, you can set a breakpoint [here](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/main/modeling_internlm_xcomposer2.py#L157).

If you want to get the output token embeddings, you can set a breakpoint [here](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/main/modeling_internlm_xcomposer2.py#L501).
