### ISSUE TITLE
Minimum GPU requirement for finetuning InternLM-XComposer2-4KHD-7B

### ISSUE THREAD

**Issue by babla9** [InternLM/InternLM-XComposer#316]
Thanks for your work! Whats the minimum GPU memory required for fine-tuning InternLM-XComposer2-4KHD-7B with and without lora? Would 4x V100 be sufficient?

**Comment by yuhangzang** [comment]
The minimum GPU memory depends on the hyper-parameter value of `max_len`, `lora_r` and `lora_alpha`. If you use very small values, you can fine-tune the model on a single 40G A100 GPU.
