### ISSUE TITLE
Lora微调4kHD模型需要的最小显存数？

### ISSUE THREAD

**Issue by ZhuangPeiyu** [InternLM/InternLM-XComposer#318]
请问使用Lora微调4kHD的模型的时候，需要的最小显存是多少呢？单卡32G无法微调，hd_num按照官方代码设置-1.

**Comment by yuhangzang** [comment]
You can reduce the value of the hyper-parameter `max_len`, `lora_r` and `lora_alpha` to save the GPU memory.
