### ISSUE TITLE
What is the difference between InternConvertedInternLMAttention and InternLMAttention?

### ISSUE THREAD

**Issue by felixfuu** [InternLM/InternLM-XComposer#32]
`InternLMAttention` is used in huggingface: https://huggingface.co/internlm/internlm-chat-7b/blob/main/modeling_internlm.py#L257
`InternConvertedInternLMAttention ` is used in this repo: https://github.com/InternLM/InternLM-XComposer/blob/main/huggingface/internlm-xcomposer/modeling_InternLM.py#L732

I set `intern_converted_llm` to false and found that the results were all wrong. What is the difference between InternConvertedInternLMAttention and InternLMAttention?

**Comment by LightDXY** [comment]
Hi, set the `intern_converted_llm` to `False` will not load the bias of the linear layers in the attention layer, the code will be cleaned in the future update.

**Comment by felixfuu** [comment]
@LightDXY I fixed this bug, but it's still wrong.
