### ISSUE TITLE
generate函数代码问题

### ISSUE THREAD

**Issue by Zking668** [InternLM/InternLM-XComposer#321]
请问generate代码是不公开的吗
![image](https://github.com/InternLM/InternLM-XComposer/assets/96710836/1d25ca49-7860-4c45-844f-1adddc4ad9f0)

**Comment by WeiminLee** [comment]
这个代码我觉得一直有问题，不知到为什么 生成\n 后就终止了。

**Comment by yuhangzang** [comment]
This function is defined in the Transformer `PretrainedModel` class. You may read the source code of the `transformer` package.
