### ISSUE TITLE
Not able to generate images

### ISSUE THREAD

**Issue by JosephKJ** [InternLM/InternLM-XComposer#323]
Is there some configuration changes that are required?
<img width="1496" alt="Screen Shot 2024-05-31 at 12 19 10 PM" src="https://github.com/InternLM/InternLM-XComposer/assets/4231550/608bf713-f059-4092-85c4-ccfdc343f33f">

Link: https://openxlab.org.cn/apps/detail/WillowBreeze/InternLM-XComposer

**Comment by yuhangzang** [comment]
We provide the Gradio demo scripts for previous models, you can build the radio demo on your own machine.
