### ISSUE TITLE
使用lora微调后变成了复读机 After lora fine tuning, my model repeat the last sentence again and again

### ISSUE THREAD

**Issue by Kyoani-0718** [InternLM/InternLM-XComposer#324]
responce: Work Together
A. Work in pairs. "Sentence Board Game"
B. Work in groups. "Find the Place"
Help
Go down this street. It will be on your left.
Go straight two blocks. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right. It will be on your left. 
Turn left. It will be on your right. 
Turn right.

**Comment by WeiminLee** [comment]
检查训练数据格式是不是正确？

**Comment by yuhangzang** [comment]
You may forget to provide the image placeholder `<ImageHere>` for the fine-tuned data. Please check the fine-tune data format.
