### ISSUE TITLE
AttributeError: 'InternLMXComposerTokenizer' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by WeiXuanLi-1024** [InternLM/InternLM-XComposer#33]
After update web_demo.py ，this error occurred

 File "/home/enbo/.cache/huggingface/modules/transformers_modules/internlm-xcomposer/tokenization_InternLM_XComposer.py", line 106, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
  File "/home/enbo/.cache/huggingface/modules/transformers_modules/internlm-xcomposer/tokenization_InternLM_XComposer.py", line 94, in vocab_size
    return self.sp_model.get_piece_size()
AttributeError: 'InternLMXComposerTokenizer' object has no attribute 'sp_model'

**Comment by myownskyW7** [comment]
This is a strange bug. Could you please share a longer error log so we can pinpoint the bug?

**Comment by WeiXuanLi-1024** [comment]
I found out why,It is because I miss downloaded tokenize.model

**Comment by myownskyW7** [comment]
Great!

**Comment by waltonfuture** [comment]
> I found out why,It is because I miss downloaded tokenize.model

I met the same problem. How do you solve it?

**Comment by Artanic30** [comment]
I solve the issue by moving the codes in tokenization_InternLM_XComposer.py:78~79 to line 66, which initialize the sp_model begore calling super().__init__()
