### ISSUE TITLE
Using in transformers results in errors

### ISSUE THREAD

**Issue by HuFY-dev** [InternLM/InternLM-XComposer#331]
Error:
`You are using a model of type internlmxcomposer2 to instantiate a model of type internlm. This is not supported for all configurations of models and can yield errors.`

Replicate: 

```python
from transformers import AutoModel
model = AutoModel.from_pretrained("internlm/internlm-xcomposer2-vl-7b", trust_remote_code=True)
```

Environment:
tried transformers=4.37.2, 4.39.1, 4.41.2

**Comment by panzhang0212** [comment]
We test the repo using transformers=4.33.1. Does the error raise with this version in your env?

**Comment by HuFY-dev** [comment]
Oh I see. I haven't tried that version before, but do you have plans to support later versions of transformers as well?

**Comment by yuhangzang** [comment]
We will support the latest versions of `transformer` in our next version (*e.g.*, IXC 3.0).
