### ISSUE TITLE
Processing of high-resolution input with InternLM-XComposer2-4KHD

### ISSUE THREAD

**Issue by mariiak2021** [InternLM/InternLM-XComposer#334]
Hi,

I'm interested in the processing of high-resolution input with InternLM-XComposer2-4KHD (especially dynamic partitioning approach). Can you point for me please where is it happening in the code? Can't locate it myself unfortunatelly.

Best,
Mariia

**Comment by LightDXY** [comment]
hi, please refer to [here](https://huggingface.co/internlm/internlm-xcomposer2-4khd-7b/blob/main/build_mlp.py#L76) and our paper
