### ISSUE TITLE
About the CLIP(freeze/unfreeze? [CLS] token available in further dev?) in InternLM-XComposer2

### ISSUE THREAD

**Issue by Coobiw** [InternLM/InternLM-XComposer#336]
Hi, thanks for your great work! I want to know whether you unfreeze the CLIPVisionEnocder during all the training stage. I want to use the [CLS] token in CLIP for further developing. Is it reasonable in InternLM-XComposer2? Thanks for your reply!

**Comment by LightDXY** [comment]
hi
1. The CLIP is tuned in all the tuning stages.
2. the CLS token is not used and not tuned, we only provide the patch tokens to the LLM
