### ISSUE TITLE
关于internlm-xcomposer2-vl模型预处理时build_mlp.py中使用torch.nn.functional.interpolate的bicubic模式的问题

### ISSUE THREAD

**Issue by lzcchl** [InternLM/InternLM-XComposer#338]
机缘巧合下发现的，即使是比较新版本的torch（我是2.1.2）也是存在这个问题的，就是resize后的图像像素会有较大的不平滑，这样会不会影响VIT模型的效果，进而导致影响整个对话效果？
这个我在torch的issues找到的 https://github.com/pytorch/vision/issues/2950，虽然这里是torchvision.transforms.Resize，但实质上还是调用torch.nn.functional.interpolate。
我测试下来的效果：可以看到下面torch.nn.functional.interpolate在右上的白色小车部分（可能还有其他不明显的位置）有黑色点，这明显是不平滑的。
原图：
![dog](https://github.com/InternLM/InternLM-XComposer/assets/34515022/94472c32-0c4d-4a32-a22c-9cafcf65058a)
pil resize 到宽高一半大小：
![pil](https://github.com/InternLM/InternLM-XComposer/assets/34515022/ea43d713-c447-4175-a94d-62c5dce75d3d)
torch.nn.functional.interpolate 到宽高一半大小：
![th2](https://github.com/InternLM/InternLM-XComposer/assets/34515022/283992a6-3b2d-4b4a-84bd-b93e6de51602)
torch.nn.functional.interpolate 参数antialias=True 到宽高一半大小：
![th1](https://github.com/InternLM/InternLM-XComposer/assets/34515022/25d27bf3-b03e-43f5-b740-081769f5d221)

我的测试代码在下方，修改img_dir就可以跑，你可以快速验证我说的这个问题。
[pil_torch_rsz.py.txt](https://github.com/user-attachments/files/15982873/pil_torch_rsz.py.txt)

**Comment by LightDXY** [comment]
hi, thanks for the comments, 插值图像在4khd里仅作为global image，模型靠后面没有resize的local图像去看细节，所以对结果的影响应该不大
