### ISSUE TITLE
Excessive Unnecessary Output in InternLM-XComposer-2.5

### ISSUE THREAD

**Issue by patrick-tssn** [InternLM/InternLM-XComposer#342]
Thank you for your great work. When testing your latest model, we find that the models always generate unnecessary, extraordinary output, demonstrating its instruction-following ability is somewhat weak.
For example, my prompt is 
```
Please generate the response as a Python dictionary string with the key "key", where the value is the string
Note: Provide only the Python dictionary string as the response without any additional text or explanation.

For example, your response should be {"key": "xxx"}
```
However, the model will generate a lot of explanation like `The image provided xxx The resulting dictionary string would be:\n ```python\n [ xxx`

**Comment by LightDXY** [comment]
thanks for the comments, we will keep improving the model
Maybe a few in-context examples will be helpful to the current model.
