### ISSUE TITLE
internlm-xcomposer2d5-7b图文写作

### ISSUE THREAD

**Issue by zhongmiyu99** [InternLM/InternLM-XComposer#343]
用了internlm-xcomposer2d5-7b图文写作给了demo，
<img width="966" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/141397259/0fcf4a9c-ceba-4a2f-89f5-3b18b60a1d88"> 出现
<img width="1166" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/141397259/a72e109d-1281-4b2c-aa9d-0787dbc04468">
可以帮忙解答一下吗？

**Comment by zhongmiyu99** [comment]
这个问题我已经解决。

**Comment by LightDXY** [comment]
bug fixed, thanks for the report.
