### ISSUE TITLE
运行图文并茂的demo报错

### ISSUE THREAD

**Issue by zhongmiyu99** [InternLM/InternLM-XComposer#344]
运行图文并茂的demo报错，可以帮忙解答一下吗？谢谢！
<img width="921" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/141397259/ba44d15e-c98a-4a94-ac03-10ba2bedc3f7">

**Comment by zhongmiyu99** [comment]
这个问题我已经解决。打扰了。

**Comment by yusirhhh** [comment]
@zhongmiyu99 怎么解决的，我有相同的问题
