### ISSUE TITLE
# I can't able to load int4 quant model

### ISSUE THREAD

**Issue by Logesh-Babu-ZS0169** [InternLM/InternLM-XComposer#345]
No module found 'auto_gptq', but its installed in my virtual enviroment. I am using python3.10 and cuda12.2.

Even though i cloned the github also. how to fix this.

**Comment by LightDXY** [comment]
the auto gptq sometimes has some waired problems, maybe you could try the https://github.com/InternLM/lmdeploy, it supports load model with 4bit
