### ISSUE TITLE
插入图片报错

### ISSUE THREAD

**Issue by zhongmiyu99** [InternLM/InternLM-XComposer#347]
运行example gradio_demo_composition.py 插入两张png 格式的图片，出现以下错误，可以帮忙看看吗？谢谢！

<img width="888" alt="image" src="https://github.com/InternLM/InternLM-XComposer/assets/141397259/2674391c-b7db-4212-9bdc-0f661e031c98">

**Comment by zhongmiyu99** [comment]
用了是2d5的模型

**Comment by LightDXY** [comment]
旧版gradio demo不支持4khd和2d5，近期会更新
