### ISSUE TITLE
运行gradio_demo_composition.py报错

### ISSUE THREAD

**Issue by zhongmiyu99** [InternLM/InternLM-XComposer#348]
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::BFloat16

模型用了internlm-xcomposer2-7b，方便解决一下吗。谢谢！

**Comment by panzhang0212** [comment]
The new gradio code has been updated, please refer to https://github.com/InternLM/InternLM-XComposer?tab=readme-ov-file#gradio-deploy
