### ISSUE TITLE
2.5 的 模型不支持 多图finetune吗

### ISSUE THREAD

**Issue by 1456416403** [InternLM/InternLM-XComposer#349]
img_embeds, img_split = self.vit(image, 
      self.plora_glb_GN, self.plora_sub_GN)
  if len(img_split) > 1:
      print ('Batch Size >1 is not supported.')
      assert 0

**Comment by yuhangzang** [comment]
No. We have already provided the multi-images fine-tuning examples, please read [the document](https://github.com/InternLM/InternLM-XComposer/tree/main/finetune).
