### ISSUE TITLE
Questions about IXC-2.5 Webpage Generation demo images

### ISSUE THREAD

**Issue by friedrichor** [InternLM/InternLM-XComposer#350]
Hello. Thanks for your excellent work!

I read your recently released paper on IXC-2.5 and I'm curious about some of the examples of webpage generation.

For Instruction-aware Webpage Generation in Figure 3. I observed that there are some images in the generated webpage. What is the source of these images? My guess is that when generating the HTML code, IXC-2.5 also generates a content-related existent image URL.

I don't know whether my guess is correct and look forward to your reply.

**Comment by tahirkanat** [comment]
I think its just takes random photos from this site "https://picsum.photos/"

**Comment by friedrichor** [comment]
Thank you for your answer.
But according to the example provided in the paper, it seems that the image is not randomly took?
When the input instruction is "Generate a website for Research institutions. The name is Shanghai AI lab." (Figure 3 in the paper), the images in the generated website are also AI-related images. I'm curious as to how to implement this.

**Comment by panzhang0212** [comment]
We use random images from unsplash.
It can return random images that meet the specified conditions by providing the dimensions and keywords of the images.
The AI-related images in Figure 3 are got by the keywords.

The similiar solution can be found by WebSight v0.2 https://huggingface.co/datasets/HuggingFaceM4/WebSight
You can get more details from https://awik.io/generate-random-images-unsplash-without-using-api/

However, unsplash stopped this service one week ago. So we replace unsplash with [picsum.photos/](https://picsum.photos/) , which could only get random image by the image size.

**Comment by friedrichor** [comment]
Thank you. I got it.

> We use random images from unsplash. It can return random images that meet the specified conditions by providing the dimensions and keywords of the images. The AI-related images in Figure 3 are got by the keywords.
> 
> The similiar solution can be found by WebSight v0.2 https://huggingface.co/datasets/HuggingFaceM4/WebSight You can get more details from https://awik.io/generate-random-images-unsplash-without-using-api/
> 
> However, unsplash stopped this service one week ago. So we replace unsplash with [picsum.photos/](https://picsum.photos/) , which could only get random image by the image size.

Thank you. I got it.
