### ISSUE TITLE
internLM-xc2.5 finetune遇到No module named 'transformers_modules.internlm_xc2'

### ISSUE THREAD

**Issue by Songlinlsl** [InternLM/InternLM-XComposer#351]
![image](https://github.com/InternLM/InternLM-XComposer/assets/45627860/7a27d11f-f848-45aa-9b7e-a656e6582173)

**Comment by simplelifetime** [comment]
Same problem here, showing No module named 'transformers_modules.internlm-xcomposer2'

**Comment by Nastu-Ho** [comment]
请问解决了吗？能否提供一下解决方案

**Comment by simplelifetime** [comment]
Don't include any "." in your checkpoint path. If you name your checkpoint directory internLM-xc2.5 you will meet such problems. Please change the directory name to internLM-xc2d5

**Comment by yuhangzang** [comment]
This issue is related to the `transformers` package rather than our fine-tuned code, please use the absolute path of the checkpoint model. Kindly re-open this issue if you still face problems.
