### ISSUE TITLE
[Broken Link] A 403 Error in Hugging Face Demo

### ISSUE THREAD

**Issue by pufanyi** [InternLM/InternLM-XComposer#354]
Hello!

Thank you for providing such an excellent model!

I noticed a minor issue in the [Hugging Face Demo](https://huggingface.co/internlm/internlm-xcomposer2d5-7b). Specifically, the link on this [line](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/39230e1e99c9b94cd639627c83e107264f4540e2/ixc_utils.py#L12) (`truetype_url`) appears to be broken. It seems that the correct URL is: [`https://huggingface.co/internlm/internlm-xcomposer2d5-7b/resolve/main/SimHei.ttf`](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/resolve/main/SimHei.ttf).

Thank you so much!

**Comment by panzhang0212** [comment]
Thanks very much.
The issue has been fixed.

**Comment by pufanyi** [comment]
Thanks!
