### ISSUE TITLE
可以开源一下XC2.5的finetune代码

### ISSUE THREAD

**Issue by yuzeng0-0** [InternLM/InternLM-XComposer#355]
可以开源一下XC2.5的finetune代码吗？4khd版本图片是336的整数倍，2.5版本是560（所以直接用之前的dataloader会报shape错误），需要用到新版的dataloader

**Comment by Nastu-Ho** [comment]
> 可以开源一下XC2.5的finetune代码吗？4khd版本图片是336的整数倍，2.5版本是560（所以直接用之前的dataloader会报shape错误），需要用到新版的dataloader

请问你解决了吗？能否提供一下相关的代码
