### ISSUE TITLE
finetune_lora.sh 报参数解析错误“ValueError: Some specified arguments are not used by the HfArgumentParser: ['name', 'or', 'path', 'of', 'data'] ”

### ISSUE THREAD

**Issue by AllenMao** [InternLM/InternLM-XComposer#359]
能提供一下完整的requirement包吗？

**Comment by AllenMao** [comment]
Yes, I am using transformer version 4.33.2 and Python version 3.8, which seems to be an error caused by "argparse".

**Comment by yongliang-wu** [comment]
Hi, I meet the same error, have you solved it?

**Comment by yongliang-wu** [comment]
You should modify the paths of finetune_lora.sh.
```sh
export MODEL=
export DATA=
```

**Comment by yuhangzang** [comment]
Kindly re-open this issue if you still face the problems.
