### ISSUE TITLE
internlm-xcomposer-7b-4bit 这个量化模型，运行失败

### ISSUE THREAD

**Issue by clevertension** [InternLM/InternLM-XComposer#36]
```python
import torch
from modelscope import snapshot_download, AutoModel, AutoTokenizer
import os

torch.set_grad_enabled(False)

# init model and tokenizer
model_dir = snapshot_download('Shanghai_AI_Laboratory/internlm-xcomposer-7b-4bit', revision = 'master')
model = AutoModel.from_pretrained(model_dir, trust_remote_code=True).cuda().eval()
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model.tokenizer = tokenizer
```

![image](https://github.com/InternLM/InternLM-XComposer/assets/346723/1a00f22c-5f13-4090-90ba-aad74c1f0ec6)

**Comment by LightDXY** [comment]
Hi, the 4-bit model need auto-gptq and use the function `from_quantized`. Please refer to the [installation instructions](https://github.com/InternLM/InternLM-XComposer/blob/main/docs/install.md) and [example](https://github.com/InternLM/InternLM-XComposer/blob/main/examples/example_chat_4bit.py)

**Comment by waltonfuture** [comment]
> Hi, the 4-bit model need auto-gptq and use the function `from_quantized`. Please refer to the [installation instructions](https://github.com/InternLM/InternLM-XComposer/blob/main/docs/install.md) and [example](https://github.com/InternLM/InternLM-XComposer/blob/main/examples/example_chat_4bit.py)

There is a bug in 4-bit inference:
No module named 'rotary_emb'

**Comment by LightDXY** [comment]
please attach the full log

**Comment by waltonfuture** [comment]
> please attach the full log

![image](https://github.com/InternLM/InternLM-XComposer/assets/98318797/4d45b8cd-0627-4394-bd19-31a2b87b326f)

**Comment by yhcao6** [comment]
@waltonfuture Hi. We have fixed the error. Please try again.

**Comment by waltonfuture** [comment]
> @waltonfuture Hi. We have fixed the error. Please try again.

Thanks. But I find that the 4-bit model still needs more than 24 GB GPU memory (I can't conduct the inference on 4090)

**Comment by myownskyW7** [comment]
@waltonfuture Please try this [4-bit example](https://github.com/InternLM/InternLM-XComposer/blob/main/examples/example_chat_4bit.py) to see the GPU memory cost. The inference code of 4-bit model is slightly different from your [script](https://github.com/InternLM/InternLM-XComposer/issues/36#issue-1941556770). Please tell us if there are other problems.

**Comment by x1ngzai** [comment]
> @waltonfuture Please try this [4-bit example](https://github.com/InternLM/InternLM-XComposer/blob/main/examples/example_chat_4bit.py) to see the GPU memory cost. The inference code of 4-bit model is slightly different from the common [usage](https://github.com/InternLM/InternLM-XComposer/issues/36#issue-1941556770). Please tell us if there are other problems.

老哥我用了4bit example的代码换成cpu执行后出现以下错误
InternLMXComposerQForCausalLM hasn't fused attention module yet, will skip inject fused attention.
InternLMXComposerQForCausalLM hasn't fused mlp module yet, will skip inject fused mlp.
Traceback (most recent call last):
  File "/home/panicboy/下载/internlm-xcomposer-7b-4bit/run.py", line 35, in <module>
    model = InternLMXComposerQForCausalLM.from_quantized(
  File "/root/anaconda3/envs/intern_clean/lib/python3.9/site-packages/auto_gptq/modeling/_base.py", line 923, in from_quantized
    model = autogptq_post_init(model, use_act_order=quantize_config.desc_act)
  File "/root/anaconda3/envs/intern_clean/lib/python3.9/site-packages/auto_gptq/modeling/_utils.py", line 258, in autogptq_post_init
    prepare_buffers(device, buffers["temp_state"], buffers["temp_dq"])
RuntimeError: no device index

意思是不能用cpu执行吗 还是设置device没设对？ 我把代码和config.json里面的device都改成cpu了

**Comment by clevertension** [comment]
> > @waltonfuture Hi. We have fixed the error. Please try again.
> 
> Thanks. But I find that the 4-bit model still needs more than 24 GB GPU memory (I can't conduct the inference on 4090)

yes, i have same issue in 4090

`OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 23.65 GiB total capacity; 22.80 GiB already allocated; 9.69 MiB free; 23.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by myownskyW7** [comment]
@x1ngzai 这个代码必须有GPU才能执行，可以用GPU再试试。

**Comment by myownskyW7** [comment]
@clevertension Do you meet this bug when run this [4-bit example](https://github.com/InternLM/InternLM-XComposer/blob/main/examples/example_chat_4bit.py)?

**Comment by clevertension** [comment]
> @clevertension Do you meet this bug when run this [4-bit example](https://github.com/InternLM/InternLM-XComposer/blob/main/examples/example_chat_4bit.py)?

yes

**Comment by myownskyW7** [comment]
@clevertension I will have a try on our 4090 GPU and will come back later.

**Comment by LightDXY** [comment]
@clevertension hi, we tried the 4-bit model and it works well on the 4090, could you provide the code and full output log you used for inference? or maybe there are any other tasks running on the same GPU?

**Comment by clevertension** [comment]
![image](https://github.com/InternLM/InternLM-XComposer/assets/346723/de7315e3-2885-4ad3-8f16-8cd300a099c7)
i have another error

![image](https://github.com/InternLM/InternLM-XComposer/assets/346723/c6573c5c-dd14-4f58-836c-da646dc17100)

**Comment by LightDXY** [comment]
1. it seems lack the tokenizer related files, such as tokenizer_config.json、special_tokens_map.json. please check all the files are downloaded.
2.  maybe it is caused by the transformer version, we tested it with transformers==4.33.1

**Comment by myownskyW7** [comment]
@clevertension 

> 1. it seems lack the tokenizer related files, such as tokenizer_config.json、special_tokens_map.json. please check all the files are downloaded.
> 2. maybe it is caused by the transformer version, we tested it with transformers==4.33.1

Please check if any of these methods can help resolve the issue. Thx!
