### ISSUE TITLE
如何调用InternLM-XComposer-2.5模型的forward函数？

### ISSUE THREAD

**Issue by qingfengcss** [InternLM/InternLM-XComposer#362]
如何给InternLM-XComposer-2.5模型喂input_ids 和labels之类的数据，直接使用forward进行推理？我想得到LLM的logits，好做教师模型，不知道能否指导一下，要是有demo就万分感谢了

**Comment by yuhangzang** [comment]
The forward function is defined in [this line](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/main/modeling_internlm_xcomposer2.py#L384) and you may refer to the [chat function](https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/main/modeling_internlm_xcomposer2.py#L564).

**Comment by yuhangzang** [comment]
Y
