### ISSUE TITLE
Why is fine-tuning so slow?

### ISSUE THREAD

**Issue by simplelifetime** [InternLM/InternLM-XComposer#371]
InternLM2-xcomposer has the same size of LLM as LLaVA-1.5 and the same CLIP. However, the fine-tuning time is almost 3.5 times slower than LLaVA-1.5. What's causing it?

**Comment by L0CUST** [comment]
Can I know how many gpu you use?

**Comment by simplelifetime** [comment]
8 x A100 80G

**Comment by yuhangzang** [comment]
Our model is designed for high-resolution and long-context inputs/outputs. You can adjust the fine-tune hyper-parameters, e.g., `hd_num`, `max_len` to accelerate.
