### ISSUE TITLE
Not able to load the finetuned model

### ISSUE THREAD

**Issue by simplelifetime** [InternLM/InternLM-XComposer#375]
I finetune InternLM-Xcomposer-2.0 with the official finetune script. However, I get the below warning when loading the finetuned model:
Some weights of InternLMXComposer2ForCausalLM were not initialized from the model checkpoint at /nas/data/jkliew/IXL-2-VL-finetuned and are newly initialized: ['model.layers.0.attention.wo.Plora_A.weight', 'model.layers.0.attention.wo.Plora_B.weight', 'model.layers.0.attention.wo.weight', 'model.layers.0.attention.wqkv.Plora_A.weight', 'model.layers.0.attention.wqkv.Plora_B.weight', 'model.layers.0.attention.wqkv.weight', 'model.layers.0.attention_norm.weight', 'model.layers.0.feed_forward.w1.Plora_A.weight', 'model.layers.0.feed_forward.w1.Plora_B.weight', 'model.layers.0.feed_forward.w1.weight', 'model.layers.0.feed_forward.w2.Plora_A.weight', 'model.layers.0.feed_forward.w2.Plora_B.weight' .....]
The output of this fine-tuned model is all random chars with no actual meaning, what's causing this error?

**Comment by zhuraromdev** [comment]
@myownskyW7 How did you solve this issue?
