### ISSUE TITLE
InternLM-XComposer-2.5 codebase

### ISSUE THREAD

**Issue by Lopa07** [InternLM/InternLM-XComposer#381]
Should we use the [InternLM-XComposer-2.0](https://github.com/InternLM/InternLM-XComposer/tree/main/InternLM-XComposer-2.0) codebase for InternLM-XComposer-2.5 as well?

**Comment by myownskyW7** [comment]
@Lopa07 Hi, I will suggest using IXC2.5 new codebase https://github.com/InternLM/InternLM-XComposer/tree/main?tab=readme-ov-file#quickstart
