### ISSUE TITLE
Bug in R560_HD18_Identity_transform

### ISSUE THREAD

**Issue by VietDunghacker** [InternLM/InternLM-XComposer#386]
In line 34-36 of the file finetune/ixc_utils.py
    scale_low = min(np.ceil(width * 1.5 / resolution), scale)
    scale_up = min(np.ceil(width * 1.5 / resolution), scale)
    scale = random.randrange(scale_low, scale_up + 1)
The value of scale_low and scale_up are literally the same, so the value of scale is exactly min(np.ceil(width * 1.5 / resolution), scale). This is a bug, is it not?

**Comment by yuhangzang** [comment]
This step is for data augmentation. We keep the same values of `scale_up` and `scale_low` during the inference stage.  If your fine-tuning dataset is relatively small, this step will not impact the results during fine-tuning.

**Comment by VietDunghacker** [comment]
Yeah, I see that this code does absolutely nothing. Thank you.
