### ISSUE TITLE
ModuleNotFoundError: No module named 'transforemrs_modules.InternLM-XComposer2'

### ISSUE THREAD

**Issue by YajieW99** [InternLM/InternLM-XComposer#390]
When I inference with InternLM-XComposer2.5-7b, this problem occured:
`ModuleNotFoundError: No module named 'transforemrs_modules.InternLM-XComposer2'`
The environment is installed as the install.md, that is, torch 2.0.1, cuda 11.7, transformers 4.33.2, torchvision 0.15.2
Is it a problem of the version of transformers?

**Comment by yuhangzang** [comment]
Can you check how you define the loading model step, e.g., `model = AutoModel.from_pretrained('internlm/internlm-xcomposer2d5-7b', xxx)`?

**Comment by YajieW99** [comment]
> Can you check how you define the loading model step, e.g., `model = AutoModel.from_pretrained('internlm/internlm-xcomposer2d5-7b', xxx)`?

I load the model using the demo provided in [https://huggingface.co/internlm/internlm-xcomposer2d5-7b](url)
![Snipaste_2024-07-22_15-53-36](https://github.com/user-attachments/assets/6448192d-f868-48bc-90f4-c5626070c4ca)

**Comment by yuhangzang** [comment]
Can you provide the full screenshot of your error? Thanks.

**Comment by YajieW99** [comment]
> Can you provide the full screenshot of your error? Thanks.

Here are the error and my model_init code:
![error](https://github.com/user-attachments/assets/feae0302-6e8c-41a9-a41f-6e6c31b77a77)
![model_init](https://github.com/user-attachments/assets/15feea8d-4952-4bfa-be76-07e759ffe5ef)

**Comment by yuhangzang** [comment]
According to your screenshot, you download the huggingface ckpt to your local path `/dataset/xxxxxxx/InternLM-XComposer2.5-7b`. Please rename the `InternLM-XComposer2.5-7b` to `InternLM-XComposer2d5-7b`, e.g., avoid using the `.` in your path.

**Comment by yuhangzang** [comment]
I hope this addresses your issue! If you have further questions, feel free to re-open this issue.
