### ISSUE TITLE
提示词生成文本问题

### ISSUE THREAD

**Issue by zhongmiyu99** [InternLM/InternLM-XComposer#392]
1、目前用InternLM-XComposer2模型做图文生成的文章，加入提示词按照不同的风格输出，好像没有多大作用。
2、比如输出风格：新闻客户端和微信公众号风格。
可以麻烦看看吗？

**Comment by zhongmiyu99** [comment]
麻烦高手可否解答一下？

**Comment by yuhangzang** [comment]
This problem may be because our training data lacks data without corresponding styles. You may list your required styles here and we may update them in our next version (`e.g.`, IXC 3.0).

**Comment by zhongmiyu99** [comment]
Ok，目前就是这两种。

**Comment by yuhangzang** [comment]
Thank to your interest in our work, we will continue to update based on the valuable community feedback!

**Comment by zhongmiyu99** [comment]
目前有没有别的解决方案可以试一下了？
