### ISSUE TITLE
build_mlp.py的后处理是否有问题

### ISSUE THREAD

**Issue by lzcchl** [InternLM/InternLM-XComposer#394]
这里以4khd模型为例，当然浦语·灵笔很多模型都有build_mlp.py这个文件，我在看代码时发现
https://huggingface.co/internlm/internlm-xcomposer2-4khd-7b/blob/main/build_mlp.py
的第103行
temp_glb_GN = sub_GN.repeat(1, H//2, 1, 1)
请问原本应该是
temp_glb_GN = glb_GN.repeat(1, H//2, 1, 1)
吗？
还是因为什么原因就是需要填sub_GN。

**Comment by LightDXY** [comment]
命名问题，图片每行换行都用sub_GN，分隔global view和local view用的才是glb_GN（https://huggingface.co/internlm/internlm-xcomposer2-4khd-7b/blob/main/build_mlp.py#L112）
