### ISSUE TITLE
模型推理速度特别慢和webui速度不一致

### ISSUE THREAD

**Issue by heiheiwangergou** [InternLM/InternLM-XComposer#40]
text = '图片里面的是谁？'
response, history = model.chat(text=text, image=image, history=None)
使用的是这个推理程序

**Comment by heiheiwangergou** [comment]
按照你们给的样例改的api接口，推理响应速度要50秒将近，webui就几秒

**Comment by heiheiwangergou** [comment]
运行你们给的examplechat也是这个速度都很慢，是有些特殊的操作嘛

**Comment by yhcao6** [comment]
@heiheiwangergou We have sped up the example chat. Please try again.

**Comment by myownskyW7** [comment]
@heiheiwangergou The inference speed problem is fixed at [HuggingFace](https://huggingface.co/internlm/internlm-xcomposer-7b/commit/18fb13d93fd89a0e1eb60d0231cdbdd73461d9f4) and [ModelSope](https://modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer-vl-7b/files/8cb686a7953b4f324cf06001c25b1b21f0adba1d). Please try the new code.

推理代码已经在[HuggingFace](https://huggingface.co/internlm/internlm-xcomposer-7b/commit/18fb13d93fd89a0e1eb60d0231cdbdd73461d9f4) 和 [ModelSope](https://modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer-vl-7b/files/8cb686a7953b4f324cf06001c25b1b21f0adba1d)修复，可以重新试一下。

**Comment by heiheiwangergou** [comment]
> @heiheiwangergou The inference speed problem is fixed at [HuggingFace](https://huggingface.co/internlm/internlm-xcomposer-7b/commit/18fb13d93fd89a0e1eb60d0231cdbdd73461d9f4) and [ModelSope](https://modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer-vl-7b/files/8cb686a7953b4f324cf06001c25b1b21f0adba1d). Please try the new code.
> 
> 推理代码已经在[HuggingFace](https://huggingface.co/internlm/internlm-xcomposer-7b/commit/18fb13d93fd89a0e1eb60d0231cdbdd73461d9f4) 和 [ModelSope](https://modelscope.cn/models/Shanghai_AI_Laboratory/internlm-xcomposer-vl-7b/files/8cb686a7953b4f324cf06001c25b1b21f0adba1d)修复，可以重新试一下。

能问一下，response, history = model.chat(text=text, image=image, history=None)，这个响应时间正常能到多少，我是A6000

**Comment by yhcao6** [comment]
example_chat.py里面有5次对话，在单张A100上测试的响应时间分别是
1. 14.06 秒
2. 7.58 秒
3. 3.26 秒
4. 4.41 秒
5. 3.52 秒

**Comment by heiheiwangergou** [comment]
> example_chat.py里面有5次对话，在单张A100上测试的响应时间分别是
> 
> 1. 14.06 秒
> 2. 7.58 秒
> 3. 3.26 秒
> 4. 4.41 秒
> 5. 3.52 秒

能问一下，cuda和torch 版本嘛，还有python版本

**Comment by yhcao6** [comment]
Python: 3.9.18
CUDA: 11.7
PyTorch: 2.0.1
CUDA_Drive: 525.60.13

**Comment by heiheiwangergou** [comment]
谢谢了，我再试一下

**Comment by heiheiwangergou** [comment]
transformers==4.33.1这个版本对嘛，大佬

**Comment by yhcao6** [comment]
可以参考这个安装文档：https://github.com/InternLM/InternLM-XComposer/blob/main/docs/install_CN.md
