### ISSUE TITLE
emm 为啥你们的模型不能判断这个13.11和13.8谁大的问题，参数量不够吗

### ISSUE THREAD

**Issue by HongLouyemeng** [InternLM/InternLM-XComposer#401]
![QQ_1721893329031](https://github.com/user-attachments/assets/da1cf662-7132-4899-a98b-a6b7f5ac64d1)
![fe3eeb84b34364115c88575f66b9ae52](https://github.com/user-attachments/assets/1451b60f-f3f8-4eee-9da3-38e90720b645)

**Comment by yuhangzang** [comment]
This ability is related to LLM rather than LVLM. Our InternLMXComposer is designed for multi-modal inputs, e.g., image and video.

**Comment by HongLouyemeng** [comment]
> This ability is related to LLM rather than LVLM. Our InternLMXComposer is designed for multi-modal inputs, e.g., image and video.

好的，谢谢解答
