### ISSUE TITLE
The feedforward dimension: BATCH_SIZE x k

### ISSUE THREAD

**Issue by YerongLi** [InternLM/InternLM-XComposer#403]
https://huggingface.co/internlm/internlm-xcomposer2d5-7b/blob/4aa81f2bbf20a9ddd4137dfe847c142adf07b652/modeling_internlm_xcomposer2.py#L444
```
                bs = len(samples['text_input'][0])
```

I found this line, the variable **bs** is not batch size.

**Comment by yuhangzang** [comment]
It doesn't matter. The variable `bs` is used to compute the loss, which requires considering all the data examples.

**Comment by YerongLi** [comment]
bs is batch size, my mistake.

**Comment by YerongLi** [comment]
@yuhangzang 
https://github.com/InternLM/InternLM-XComposer/issues/404
In the Dataset.get_item() keeping the self.batch_size does not really make sense. Can we disable it with one PR?
