### ISSUE TITLE
大佬，发现一个examplechat的新问题，api服务单次请求速度提上来了，请求次数多了以后，速度会变慢

### ISSUE THREAD

**Issue by heiheiwangergou** [InternLM/InternLM-XComposer#42]
如何解决

**Comment by heiheiwangergou** [comment]
![image](https://github.com/InternLM/InternLM-XComposer/assets/45333312/e53d3db0-2154-4f6c-a25a-ae24031fd19c)
显卡的利用率一直拉不满

**Comment by heiheiwangergou** [comment]
![adf86c0d67633a6f8a65d1343e51e87](https://github.com/InternLM/InternLM-XComposer/assets/45333312/8d8bfd27-86f9-4d37-bddc-18925c84eb5a)
有的请求速度快，有的请求速度慢

**Comment by heiheiwangergou** [comment]
不同的prompt也会影像返回速度，这个能优化嘛

**Comment by heiheiwangergou** [comment]
帮我根据图片提炼出5个关键词,用逗号分隔,我输入这个prompt就是60多秒返回，我输入：这个图片里面有什么，就是3秒返回，这个是什么原因

**Comment by yhcao6** [comment]
> ![adf86c0d67633a6f8a65d1343e51e87](https://user-images.githubusercontent.com/45333312/276059755-8d8bfd27-86f9-4d37-bddc-18925c84eb5a.jpg) 有的请求速度快，有的请求速度慢

 可以发下你的测试脚本吗，我试试。

不同的prompt模型可能生成的内容长度也不一样，有些比较长，就慢点；有些比较短，就比较快。

**Comment by heiheiwangergou** [comment]
from fastapi import FastAPI
from pydantic import BaseModel
import requests
import os
import torch

from modelscope import snapshot_download, AutoModel, AutoTokenizer
import uvicorn
import time

torch.set_grad_enabled(False)

# init model and tokenizer
model_dir = snapshot_download('Shanghai_AI_Laboratory/internlm-xcomposer-7b')
model = AutoModel.from_pretrained(model_dir, trust_remote_code=True).cuda().eval()
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model.tokenizer = tokenizer

app = FastAPI()


class ImageText(BaseModel):
    url: str
    text: str


@app.post("/download_image")
async def download_image(img_txt: ImageText):
    url = img_txt.url
    text = img_txt.text
    save_path = '路径/images/'

    start_time = time.time()
    response = requests.get(url)
    if response.status_code == 200:
        with open(os.path.join(save_path, 'downloaded_image.jpg'), 'wb') as f:
            f.write(response.content)
    end_time = time.time()
    imgtime=end_time-start_time
    print(imgtime)
    image = '路径/downloaded_image.jpg'

    # init model and tokenizer
    # response, history = model.chat(text=text, image=image, history=None)
    response = model.generate(text, image)
    #print(response)
    end1time= time.time()
    costtime=end1time-start_time
    print(costtime)
    return response

**Comment by heiheiwangergou** [comment]
`from fastapi import FastAPI
from pydantic import BaseModel
import requests
import os
import torch

from modelscope import snapshot_download, AutoModel, AutoTokenizer
import uvicorn
import time

torch.set_grad_enabled(False)

# init model and tokenizer
model_dir = snapshot_download('Shanghai_AI_Laboratory/internlm-xcomposer-7b')
model = AutoModel.from_pretrained(model_dir, trust_remote_code=True).cuda().eval()
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model.tokenizer = tokenizer

app = FastAPI()


class ImageText(BaseModel):
    url: str
    text: str


@app.post("/download_image")
async def download_image(img_txt: ImageText):
    url = img_txt.url
    text = img_txt.text
    save_path = '路径/images/'

    start_time = time.time()
    response = requests.get(url)
    if response.status_code == 200:
        with open(os.path.join(save_path, 'downloaded_image.jpg'), 'wb') as f:
            f.write(response.content)
    end_time = time.time()
    imgtime=end_time-start_time
    print(imgtime)
    image = '路径/downloaded_image.jpg'

    # init model and tokenizer
    # response, history = model.chat(text=text, image=image, history=None)
    response = model.generate(text, image)
    #print(response)
    end1time= time.time()
    costtime=end1time-start_time
    print(costtime)
    return response

`

**Comment by heiheiwangergou** [comment]
大佬，有空帮我看看

**Comment by yhcao6** [comment]
https://github.com/InternLM/InternLM-XComposer/blob/f16af9b3c76695f780cd25a037fa51b86ebe8711/huggingface/internlm-xcomposer-vl/modeling_InternLM_XComposer.py#L36-L44

如果你不需要模型生成很长的内容，可以尝试调整下 length_penalty 和 max_new_tokens 这2个参数，比如 length_penalty 设置为2，max_new_tokens 设置为100，这样速度应该会快很多。你可以在脚本里面直接这样改：

```
model.gen_config['length_penalty'] = 2
model.gen_config['max_new_tokens'] = 100
```

**Comment by heiheiwangergou** [comment]
好的，大佬我试一下

**Comment by heiheiwangergou** [comment]
num_beams=5, 
     do_sample=False, 
     min_length=1, 
     repetition_penalty=1.5, 
     length_penalty=1.0, 
     temperature=1.0, 
     max_new_tokens=500, 大佬能详细解释一下这几个参数嘛

**Comment by heiheiwangergou** [comment]
大佬再问个问题，webui的服务底层和examplechat有啥区别嘛，webui问什么问题返回的都很快，想学习一下

**Comment by yhcao6** [comment]
webui 用的是流式(streaming)的方式，模型生成一点，返回一点；example_chat是等模型生成完再一次性返回，所以你觉得等待时间更久了。
