### ISSUE TITLE
请问可以部署多卡4090的推理吗？

### ISSUE THREAD

**Issue by waltonfuture** [InternLM/InternLM-XComposer#44]
单卡显存不够

**Comment by panzhang0212** [comment]
Repo支持了多卡部署，两张3090或者4090可部署全量模型，请pull最新代码，按照[this guide](https://github.com/InternLM/InternLM-XComposer#inference-on-multiple-gpus)执行代码。
The Repo now supports multi-gpus deployment. Two 3090 or 4090 gpus can deploy the full model. Please pull the latest code and execute the code according to [this guide](https://github.com/InternLM/InternLM-XComposer#inference-on-multiple-gpus).

**Comment by waltonfuture** [comment]
> Repo支持了多卡部署，两张3090或者4090可部署全量模型，请pull最新代码，按照[this guide](https://github.com/InternLM/InternLM-XComposer#inference-on-multiple-gpus)执行代码。 The Repo now supports multi-gpus deployment. Two 3090 or 4090 gpus can deploy the full model. Please pull the latest code and execute the code according to [this guide](https://github.com/InternLM/InternLM-XComposer#inference-on-multiple-gpus).

谢谢！请问这个可以用modelscope的模型来进行多卡部署吗？我看代码里面只写了基于huggingface的

**Comment by rexainn** [comment]
找不到那个guide的连接了
