### ISSUE TITLE
不支持同时输入多张图片？

### ISSUE THREAD

**Issue by PsyQuant** [InternLM/InternLM-XComposer#45]
试了一下huggingface上的demo，请问是不能同时上传多张图片让模型来识别吗？

**Comment by panzhang0212** [comment]
你是指一个问题包含多张图片吗？当前的demo没有支持一次输入多张图片。
Do you mean a question contains multiple images? The current demo does not support inputting multiple images at once.

**Comment by PsyQuant** [comment]
> 你是指一个问题包含多张图片吗？当前的demo没有支持一次输入多张图片。 Do you mean a question contains multiple images? The current demo does not support inputting multiple images at once.
是的，比如问多张图片中的人物是不是同一个人。目前模型是不支持是吧？

**Comment by myownskyW7** [comment]
@PsyQuant 在聊天的过程中，前面给模型的图片，再输入新的图片后模型也能看到，所以两张图片对比这种问题模型也能回答一些。不过这种情况我们在训练过程中没有特别处理，因此没法保证模型回答多图问题的质量。

**Comment by starxhong** [comment]
比如给一组图片，提取其中的相似点，或者哪个最亮这样，目前看起来还不能支持？
