### ISSUE TITLE
According to the tutorial and official docker image, sh start.sh has the following error:

### ISSUE THREAD

**Issue by lwlovelmm** [InternLM/InternLM-XComposer#458]
![屏幕截图 2024-12-18 210018](https://github.com/user-attachments/assets/eb5e1688-e0cb-4d93-84a8-2d15cfb94e4e)

Will both 1 and 2 affect the operation? What should I do? Thank you for your answer

**Comment by yhcao6** [comment]
For 1, we built the docker in cuda12 environment. You can either reinstall VLLM or download cuda12.

For 2, please run ```python examples/merge_lora.py``` to get the merged_lora model. We have upgrade the README. Please check it again.

**Comment by lwlovelmm** [comment]
I have reviewed and followed the upgrade README, but I still get strange errors：
![屏幕截图 2024-12-19 144126](https://github.com/user-attachments/assets/fcd72f5f-a235-4078-acf9-f6b2b1334d39)
![Uploading 屏幕截图 2024-12-19 144102.png…]()

**Comment by lwlovelmm** [comment]
![屏幕截图 2024-12-19 144102](https://github.com/user-attachments/assets/dff05c10-9a13-4882-9ba0-ae23a58dc524)
