### ISSUE TITLE
No response using model.chat

### ISSUE THREAD

**Issue by xyz189411yt** [InternLM/InternLM-XComposer#49]
Hi, I'm using internLM-XComposer to generate some data and I have tried your demo, it works fine when I'm using model.generate.
But when I using model.chat(), model can only reply to the first call, subsequent calls are unresponsive and return empty string.

I'm using:
torch==2.0.1
transformers==4.33.2

My hardware is a single 3090 with 24G GPU memory, so I use 4-bit quantized models and tried your examples/example_chat_4bit.py and find this issue.

Is my environmental issue causing this problem or something else?

**Comment by xyz189411yt** [comment]
I've just figure out a bit.
When I used the origional cases in my code(The aiyinsitan case), my code worked perfectly.
It terns out that mayby the max length limits caused the model to reject the following answers.

The new issue is how can I remove this limit? Or is there another deep reason to cause this problem?

**Comment by LightDXY** [comment]
hi, it may caused by the max sequence length (2048 now), can you provide code and detailed log of the failure case?
