### ISSUE TITLE
example_demo code contains inter information

### ISSUE THREAD

**Issue by pixas** [InternLM/InternLM-XComposer#5]
Hi, you seem to leave extra information in L51 and L52 in `examples/web_demo.py`:
```python
 self.llm_model = AutoModel.from_pretrained('/mnt/petrelfs/share_data/dongxiaoyi/share_models/release_chat', trust_remote_code=True)
        tokenizer = AutoTokenizer.from_pretrained('/mnt/petrelfs/share_data/dongxiaoyi/share_models/release_chat', trust_remote_code=True)
```
in the web_demo.py.
You may want to fix them to avoid the exposure.

**Comment by myownskyW7** [comment]
Thank you for your kind reminder. The bug is now resolved. https://github.com/InternLM/InternLM-XComposer/commit/3c8e940d700f4ec7a17c0a28e997ff90eca63161
