### ISSUE TITLE
How to get the embedding_matrix of the model  and text embeddings?

### ISSUE THREAD

**Issue by tcexeexe** [InternLM/InternLM-XComposer#50]
Hello~
   I want to get the embedding matrixand of the model and the embeddings when l input a text. Can you tell me how to get it?
l have tried "model.embed_tokens.weight" and “model.model.embed_tokens(input)” but it failed.

**Comment by LightDXY** [comment]
Hi, it should be `model.internlm_model.model.embed_tokens.weight`
