### ISSUE TITLE
请问现在支持中文数据SFT吗？

### ISSUE THREAD

**Issue by LianghuiGuo** [InternLM/InternLM-XComposer#54]
请问现在有SFT的教程嘛？支持中文数据微调么？

**Comment by myownskyW7** [comment]
@LianghuiGuo 🎉 Please check the finetuning code here https://github.com/InternLM/InternLM-XComposer?tab=readme-ov-file#finetuning

**Comment by LianghuiGuo** [comment]
> @LianghuiGuo 🎉 Please check the finetuning code here https://github.com/InternLM/InternLM-XComposer?tab=readme-ov-file#finetuning

好的，谢谢！
