### ISSUE TITLE
多轮对话网页端和终端结果不符，且终端执行时部分结果为空

### ISSUE THREAD

**Issue by cloudyuyuyu** [InternLM/InternLM-XComposer#58]
请教一个问题：同样的4个question，在网页端可以有比较好的结果，但是在Notebook中执行，第4个answer的结果就为空。尝试其他多轮对话也会出现类似的情况，但不一定是第4个answer，可能是第3个或其他位置为空。
网页端：
![image](https://github.com/InternLM/InternLM-XComposer/assets/16486492/3d6ee18d-b615-4853-8e84-44c8f9c40628)

终端：
![image](https://github.com/InternLM/InternLM-XComposer/assets/16486492/d09c9bfb-9cf8-44d5-bac8-871bffdbf195)

**Comment by myownskyW7** [comment]
We kindly request that you attach your current code, and we will review it as soon as possible. Please ensure that your code is properly formatted and free of any errors. Thank you.

**Comment by cloudyuyuyu** [comment]
> We kindly request that you attach your current code, and we will review it as soon as possible. Please ensure that your code is properly formatted and free of any errors. Thank you.
`import torch
from transformers import AutoModel, AutoTokenizer

torch.set_grad_enabled(False)

# init model and tokenizer
model = AutoModel.from_pretrained('./internlm_xcomposer_model', trust_remote_code=True).cuda().eval()
tokenizer = AutoTokenizer.from_pretrained('./internlm_xcomposer_model', trust_remote_code=True)
model.tokenizer = tokenizer


image = './aiyinsitan.jpg'

# Multi-Turn Text-Image Dialogue
# 1st turn
text = '图片里面的是谁？'
response, history = model.chat(text=text, image=image, history=None)
print(response)
# 图片里面的人物是阿尔伯特·爱因斯坦（Albert Einstein），一位著名的物理学家和理论物理学家。

# 2nd turn
text = '他有哪些成就?'
response, history = model.chat(text=text, image=None, history=history)
print(response)
# 阿尔伯特·爱因斯坦是20世纪最伟大的物理学家之一，他提出了狭义相对论和广义相对论，为现代物理学的发展做出了巨大的贡献。
# 此外，他还提出了光量子理论、质能关系等重要理论，对现代物理学的发展产生了深远的影响。

# 3rd turn
text = '他是最伟大的物理学家吗?'
response, history = model.chat(text=text, image=None, history=history)
print(response)
# 是的，阿尔伯特·爱因斯坦是20世纪最伟大的物理学家之一。他提出了狭义相对论和广义相对论，为现代物理学的发展做出了巨大的贡献。

# 4th turn
text = '和他同时期的物理学家有哪些?'
response, history = model.chat(text=text, image=None, history=history)
print(response)
`

![image](https://github.com/InternLM/InternLM-XComposer/assets/16486492/698dce91-de9f-4a3f-9752-8af46df25dc6)

**Comment by cloudyuyuyu** [comment]
@myownskyW7

**Comment by myownskyW7** [comment]
@cloudyuyuyu InternLM-XComposer2 is much more powerful that its 1.0 version. Please check how to use it here https://github.com/InternLM/InternLM-XComposer?tab=readme-ov-file#quickstart
