### ISSUE TITLE
Which model is used as the Share Captioner in ShareGPT4V?

### ISSUE THREAD

**Issue by jzhang38** [InternLM/InternLM-XComposer#62]
Great work and congrat!
Can I ask which model is used as the captioner in ShareGPT4V data generation? Seems that the paper does not mention it very clearly.

**Comment by LightDXY** [comment]
Hi, thanks for your interest, the Share-Captioner is fine-tuned from a high-resolution InternLM-XComposer, the details will be released in the following.

**Comment by Gutianpei** [comment]
Hello Author(s), nice work! Have you evaluate the captioning capability of Share-Captioner and ShareGPT4V-7B? Curious if the performance downgrades after training on generated data by the Captioner.

**Comment by LightDXY** [comment]
hi, thanks for your interest
1. We use a user study to evaluate the caption performance, the Share-Captioner performs on par with GPT4-Vision (table.2 in our paper)
2. ShareGPT4V-7B is a generalist model for multi-modal tasks, so its caption performance is not specifically evaluated
3. The ShareGPT4V-7B is pretrained on the ShareGPT4V-PT (1.2M generated by the Captioner), Table.5 shows the effectiveness of these high-quality captions, compared with short captions generated by BLIP.

**Comment by Gutianpei** [comment]
> hi, thanks for your interest
> 
> 1. We use a user study to evaluate the caption performance, the Share-Captioner performs on par with GPT4-Vision (table.2 in our paper)
> 2. ShareGPT4V-7B is a generalist model for multi-modal tasks, so its caption performance is not specifically evaluated
> 3. The ShareGPT4V-7B is pretrained on the ShareGPT4V-PT (1.2M generated by the Captioner), Table.5 shows the effectiveness of these high-quality captions, compared with short captions generated by BLIP.

Thanks for the reply, it was a great explanation. I noticed a clear degradation when asking ShareGPT4V-7B to caption the sample image used in the homepage, it's interesting this happens since ideally the two model should have same captioning capability. Thanks for the work again!
