### ISSUE TITLE
question about ShareGPT4V dataset

### ISSUE THREAD

**Issue by TyRantLQlyf** [InternLM/InternLM-XComposer#63]
where can I get the images in ShareGPT4V dataset.

**Comment by LightDXY** [comment]
hi, thanks for your interest, you could find it at `https://huggingface.co/datasets/Lin-Chen/ShareGPT4V`

**Comment by TyRantLQlyf** [comment]
> hi, thanks for your interest, you could find it at `https://huggingface.co/datasets/Lin-Chen/ShareGPT4V`

@LightDXY hi, thanks for your reply.  I still need your help. in the JSON files, I found these image paths :
web-celebrity, share_textvqa, web-landmark, sam
I would like to know which datasets correspond to these paths.

**Comment by maqy1995** [comment]
@LightDXY hi, I also have a question about the dataset. The dataset part of the paper on arxiv said that More details could be found in the supplementary materials. But I cant find where the supplementary materials is. Could you please offer me a link?

**Comment by xiaoachen98** [comment]
> @LightDXY hi, I also have a question about the dataset. The dataset part of the paper on arxiv said that More details could be found in the supplementary materials. But I cant find where the supplementary materials is. Could you please offer me a link?

Hi, you can find it in this link https://arxiv.org/pdf/2311.12793.pdf

**Comment by OpenJarvisAI** [comment]
Smae here, WHERE IS THE FUCKING share_textvqa?

**Comment by xiaoachen98** [comment]
> Smae here, WHERE IS THE FUCKING share_textvqa?

Chill out dude, if you have followed our guidelines and opened the link to our [web data](https://drive.google.com/drive/folders/1tCUQ-sq6vdshZVkF0ZeF3K4eztkXJgax), you would have found it already. 
![屏幕截图 2024-04-12 213644](https://github.com/InternLM/InternLM-XComposer/assets/56393454/246e359c-0574-4fb6-8159-a3b1f91a657c)
Hope you can put your rude energy into patience.  :)
