### ISSUE TITLE
An example with Transformers to generate text + images

### ISSUE THREAD

**Issue by jordilinarespellicer** [InternLM/InternLM-XComposer#7]
Hi,

I see very interesting the examples detailed for interacting with images with Transformers for VQA etc. However, how can we really generate text + images (with the right history context) with HF transformers?

I cannot see an example with this good feature of your work.

Thanks.

**Comment by LightDXY** [comment]
Hi, thanks for your attention. As we showed in Fig.3 in our paper(https://arxiv.org/pdf/2309.15112v2.pdf), the text-image interleaved generation is realized by multiple steps. The model first generates the text, then generates proper positions and corresponding captions for image injection. After we get candidate images by retrieval method, the model selects the best one based on the context text and images. For more details, please refer to our paper. For the code, please see our online demo(https://github.com/InternLM/InternLM-XComposer/blob/main/demo_asset/demo.md).
