### ISSUE TITLE
I would like to know how to use GPT4V to build the ShareGPT4V data set. Will the construction code or prompt be open source?

### ISSUE THREAD

**Issue by xulinui** [InternLM/InternLM-XComposer#71]

**Comment by LightDXY** [comment]
hi, thanks for your interest. The base prompt, data source specific prompt, and detailed data source will be open source in the following updates.

**Comment by BenQLange** [comment]
Has it been open-sourced already? If yes, can you point to the script?

> hi, thanks for your interest. The base prompt, data source specific prompt, and detailed data source will be open source in the following updates.
