### ISSUE TITLE
Could you please provide a simple scripts to run the image caption with Share-gpt4 model like other famous huggingface models?

### ISSUE THREAD

**Issue by xinsir6** [InternLM/InternLM-XComposer#72]
![image](https://github.com/InternLM/InternLM-XComposer/assets/128811208/ef6dc753-7e3d-4c0d-88ac-8364a00ff539)
could you provide a similar scripts like bilp2

**Comment by LightDXY** [comment]
Hi, thanks for your interest, ShareGPT4V-7B is a general model. 
The high-quality caption in our ShareGPT4V-PT is generated by Share-Captioner, a specialist model for captioning.
The Share-Captioner will be released in the following update. Btw, The online demo is available now: https://huggingface.co/spaces/Lin-Chen/Share-Captioner

**Comment by xiaoachen98** [comment]
> ![image](https://private-user-images.githubusercontent.com/128811208/285093665-ef6dc753-7e3d-4c0d-88ac-8364a00ff539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjA1NTQsIm5iZiI6MTcwMjQ2MDI1NCwicGF0aCI6Ii8xMjg4MTEyMDgvMjg1MDkzNjY1LWVmNmRjNzUzLTdlM2QtNGMwZC04OGFjLTgzNjRhMDBmZjUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwOTM3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDhlYWQ5OWZiMDFlNzY5MWMwY2U1MjIyNjFiZTUyMzhiNTc2MTc3MzhjMmQ4OTM4YmNhYmQyODZmZDc3YzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HyMnj4z5vk2rQ_S-k7mn0uU69zImqebVKBPIGlMIIrE) could you provide a similar scripts like bilp2

Hi. ShareCaptioner is available now! And we also support batch inference.
