### ISSUE TITLE
about your image datasets

### ISSUE THREAD

**Issue by chuangzhidan** [InternLM/InternLM-XComposer#74]
regarding your datasets ,
coco/train2017/000000000025.jpg
how do i locate the image,where can i find them? thanks

**Comment by htian01** [comment]
Same for llava images, for example: 
llava/llava_pretrain/images/00011/000114116.jpg
However the original llava is for example:
GCC_train_000554386.jpg

I've confirmed that 000114116.jpg is not GCC_train_000114116.jpg

**Comment by LightDXY** [comment]
hi, you could download the coco2017 dataset from its official website(https://cocodataset.org/#home)

**Comment by TyRantLQlyf** [comment]
> hi, you could download the coco2017 dataset from its official website(https://cocodataset.org/#home)

@LightDXY  Hi，how do i locate the images which paths start with web-celebrity、share_textvqa、 web-landmark or wikiart？

**Comment by GradientGuru** [comment]
> > > hi, you could download the coco2017 dataset from its official website(https://cocodataset.org/#home)
> > 
> > 
> > @LightDXY Hi，how do i locate the images which paths start with web-celebrity、share_textvqa、 web-landmark or wikiart？
> 
> Hi, you can find these data in this link: https://drive.google.com/drive/folders/1tCUQ-sq6vdshZVkF0ZeF3K4eztkXJgax. We have written the details about managing data in the sharegpt4v readme.

it would be nice if you upload the 20K images from SA-1B into google drive too..

**Comment by peace-zy** [comment]
> > > hi, you could download the coco2017 dataset from its official website(https://cocodataset.org/#home)
> > 
> > 
> > @LightDXY Hi，how do i locate the images which paths start with web-celebrity、share_textvqa、 web-landmark or wikiart？
> 
> Hi, you can find these data in this link: https://drive.google.com/drive/folders/1tCUQ-sq6vdshZVkF0ZeF3K4eztkXJgax. We have written the details about managing data in the sharegpt4v readme.

could you provide a Baidu cloud disk link or huggingface link

**Comment by chuangzhidan** [comment]
> hi, you could download the coco2017 dataset from its official website(https://cocodataset.org/#home)


yes, but different filename now,yes? unable to find that exact picture anymore
