### ISSUE TITLE
When will the Share-Captioner model be released ? Thanks !

### ISSUE THREAD

**Issue by liuyuyuil** [InternLM/InternLM-XComposer#75]

**Comment by liuyuyuil** [comment]
Great Job! But what base caption model the Share-Captioner used for finetuning? There is no information mentioned in the paper. Thanks!

**Comment by shipengai** [comment]
+1 The paper about Share-Captioner？

**Comment by LightDXY** [comment]
Hi, thanks for your interest, the Share-Captioner is fine-tuned from a high-resolution InternLM-XComposer, the details will be released in the following update. Btw, The online demo is available now: https://huggingface.co/spaces/Lin-Chen/Share-Captioner

**Comment by Gutianpei** [comment]
> Hi, thanks for your interest, the Share-Captioner is fine-tuned from a high-resolution InternLM-XComposer, the details will be released in the following update. Btw, The online demo is available now: https://huggingface.co/spaces/Lin-Chen/Share-Captioner

Thanks for the update! Is there an expected date to release the code and weight of Share-Captioner?

**Comment by devilismyfriend** [comment]
+1 on that

**Comment by tongyujun1999** [comment]
> Hi, thanks for your interest, the Share-Captioner is fine-tuned from a high-resolution InternLM-XComposer, the details will be released in the following update. Btw, The online demo is available now: https://huggingface.co/spaces/Lin-Chen/Share-Captioner

What' the performance difference between the InternLM-XComposer and ShareGPT4V? Can we assume that there is a distillation relationship between the two models?

**Comment by xiaoachen98** [comment]
Hi. ShareCaptioner is available now! And we also support batch inference.
