### ISSUE TITLE
Video QA with InternLM-XComposer and Fine-tuning Code Availability

### ISSUE THREAD

**Issue by ZhouZineng** [InternLM/InternLM-XComposer#8]
1、How does InternLM-XComposer handle video QA? The examples seem to only involve images.
2、Will the fine-tuning code be open-sourced soon?

**Comment by LightDXY** [comment]
Thanks for your attention. 
1. Video is not supported for our model now, but many ways exist to extend our model to understand videos, such as the image-band.
2. The open source of the fine-tuning code is on the way.
