### ISSUE TITLE
「ShareGPT4V」Question about Pretraing？

### ISSUE THREAD

**Issue by shipengai** [InternLM/InternLM-XComposer#82]
论文中，在pretraing阶段，vit mlp llm都微调；有没有和只有mlp微调的对比实验。

**Comment by xiaoachen98** [comment]
> 论文中，在pretraing阶段，vit mlp llm都微调；有没有和只有mlp微调的对比实验。

![image](https://github.com/InternLM/InternLM-XComposer/assets/56393454/e749e7c6-840a-4de5-8173-5a60964e8997)
You can refer to the result in the first column of Table 6.
