### ISSUE TITLE
「ShareGPT4V」about SAM dataset?

### ISSUE THREAD

**Issue by ZoneFv** [InternLM/InternLM-XComposer#84]
SAM dataset (Only the first 50 parquets have been used so far.)，What does this sentence mean? 
sa_000000.tar、sa_000001.tar ……  a_000049.tar  in the SAM Download text file?

**Comment by ZoneFv** [comment]
我们下载了sa_000000.tar、sa_000001.tar …… a_000049.tar，发现很多图片不在这个集合里，能够提供这50个具体的tar文件名？

**Comment by xiaoachen98** [comment]
Sorry for the mistake. In fact, we used the first 51 zips from 0-50. Thanks for your feedback, we will correct this in the readme file.
