### ISSUE TITLE
Share-Captioner 模型能不能开源

### ISSUE THREAD

**Issue by bagewell** [InternLM/InternLM-XComposer#89]
你好，想请教一下Share-Captioner 用的基础模型是用的什么，Share-Captioner 模型能不能开源

**Comment by tongyujun1999** [comment]
+1同问，share-captioner和ShareGPT4V-7B 区别在哪

**Comment by shams2023** [comment]
+1 想要使用Share-Captioner来完成任务

**Comment by Lanyu0303** [comment]
+1

**Comment by xiaoachen98** [comment]
Hi. ShareCaptioner is available now! And we also support batch inference.
