### ISSUE TITLE
Is it possible to perform batch image captioning tasks?

### ISSUE THREAD

**Issue by shams2023** [InternLM/InternLM-XComposer#92]
I suddenly discovered this treasure model and would like to ask if it is possible to implement the image captioning task?
The images in my dataset have very low pixels and are generally blurry (size: 60 * 160). The image example is as follows:
![image](https://github.com/InternLM/InternLM-XComposer/assets/141383792/bdffeeec-ec19-445d-a59b-cedd3c7ce333)
![image](https://github.com/InternLM/InternLM-XComposer/assets/141383792/7d0aa6dc-addd-48f6-9d1c-fcbd8f4a4ff0)

Can use your model to perform batch image captioning tasks on the images in my dataset?
I am very much looking forward to your reply. Thank you for your work, he is excellent!

**Comment by xiaoachen98** [comment]
Hi. ShareCaptioner is available now! And we also support batch inference.

**Comment by xiaoachen98** [comment]
> I suddenly discovered this treasure model and would like to ask if it is possible to implement the image captioning task? The images in my dataset have very low pixels and are generally blurry (size: 60 * 160). The image example is as follows: ![image](https://private-user-images.githubusercontent.com/141383792/287519705-bdffeeec-ec19-445d-a59b-cedd3c7ce333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjA0OTEsIm5iZiI6MTcwMjQ2MDE5MSwicGF0aCI6Ii8xNDEzODM3OTIvMjg3NTE5NzA1LWJkZmZlZWVjLWVjMTktNDQ1ZC1hNTliLWNlZGQzYzdjZTMzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwOTM2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDRlNmVhYzQ2MTdhYjZlOGNlNDRmZmNmZTBlYmVkN2IwNWQ1YTFjZTdiOWYwY2NjZGE1Y2U5N2FkM2MxOGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j2Q2iyvEfPQv8OaV1W_3iYgaFBvRkoB9rCX1nT6JSTI) ![image](https://private-user-images.githubusercontent.com/141383792/287519737-7d0aa6dc-addd-48f6-9d1c-fcbd8f4a4ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjA0OTEsIm5iZiI6MTcwMjQ2MDE5MSwicGF0aCI6Ii8xNDEzODM3OTIvMjg3NTE5NzM3LTdkMGFhNmRjLWFkZGQtNDhmNi05ZDFjLWZjYmQ4ZjRhNGZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwOTM2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTU1OTc4Mjk3NzMxYmFlOWYxOTY1MWIwMTQ2MDdhOTRkMWZhNGEwYTkxNmJhZjA4OGQ4MGE2Y2UxM2JjYTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u-TOzmnr_NQNp7HOz4FqmKUjdnkShcDhQ7Ros5HqG_I)
> 
> Can use your model to perform batch image captioning tasks on the images in my dataset? I am very much looking forward to your reply. Thank you for your work, he is excellent!

Hi. ShareCaptioner is available now! And we also support batch inference.
