### ISSUE TITLE
something wrong when running huggingface demo

### ISSUE THREAD

**Issue by computerfix** [InternLM/InternLM-XComposer#95]

**Comment by xiaoachen98** [comment]
> model = AutoModel.from_pretrained('Lin-Chen/ShareGPT4V-7B') File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained config, kwargs = AutoConfig.from_pretrained( File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 998, in from_pretrained config_class = CONFIG_MAPPING[config_dict["model_type"]] File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 710, in **getitem** raise KeyError(key) KeyError: 'llava'

You should follow the LLaVA repo to build an LMM model.

from llava.model.builder import load_pretrained_model
from llava.mm_utils import get_model_name_from_path
from llava.eval.run_llava import eval_model

model_path = "Lin-Chen/ShareGPT4V-7B"

tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path=model_path,
    model_base=None,
    model_name=get_model_name_from_path(model_path)
)
