### ISSUE TITLE
About the SAM dataset

### ISSUE THREAD

**Issue by YifanXu74** [InternLM/InternLM-XComposer#96]
Hi,

``"the SAM dataset (Only the first 51 (i.e., 0-50) parquets"``

I am still somewhat confused about this. Is this referring to the file named {000000:000050}.tar, or the content of the first 51 lines in the official text file?

**Comment by xiaoachen98** [comment]
> 000000:000050

Sorry for the confusion. We utilize 000000:000050 files.

**Comment by YifanXu74** [comment]
Got it. Many thanks!
