### ISSUE TITLE
[ShareGPT4V] Can you release the pretrained checkpoint?

### ISSUE THREAD

**Issue by TideDra** [InternLM/InternLM-XComposer#98]
I want to fine-tune your model pretrained on ShareGPT4V-PT on my own instruction-following dataset, for a fair performance comparison. Can you release the pretrained checkpoint?

**Comment by Lanyu0303** [comment]
+1
mark

**Comment by xiaoachen98** [comment]
The pretrained checkpoint is available at https://huggingface.co/Lin-Chen/ShareGPT4v-7B_Pretrained_vit-large336-l12_vicuna-7b-v1.5. Enjoy it!
